name: aws_credentials_provider_ini
description: AWS credential provider that sources credentials from ~/.aws/credentials and ~/.aws/config
version: 1.0.0
homepage: https://github.com/agilord/aws_client/tree/master/aws_credentials_provider_ini

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  aws_sts_api: ^1.0.0

dev_dependencies:
  lints: ^1.0.0

dependency_overrides:
  shared_aws_api:
    path: ../shared_aws_api