name: aws_client_generator
description: Code generator for package:aws_client
version: 0.2.0
publish_to: none

environment:
  sdk: '^3.0.0'

dependencies:
  analyzer: ^6.0.0
  archive: ^3.0.0
  args: ^2.2.0
  collection: ^1.17.2
  dart_style: ^2.0.0
  html: ^0.15.0
  http: ^1.0.0
  json_annotation: ^4.4.0
  path: ^1.7.0
  pool: ^1.4.0
  process_runner: ^4.0.0
  source_helper: ^1.3.3
  version: ^3.0.0
  yaml: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.1.1
  build_verify: ^3.0.0
  json_serializable: ^6.1.3
  test: ^1.0.0
