name: aws_client.generator
description: Code generator for package:aws_client
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  archive:
  args:
  html:
  http:
  json_annotation:
  path:
  pool:
  process_runner:

dev_dependencies:
  analyzer:
  pedantic:
  build_runner:
  json_serializable:
  test:
  dart_style:
  yaml:
  meta: