name: aws_client.generator
description: Code generator for package:aws_client
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  archive: ^2.0.11
  args: ^1.5.2
  html: ^0.14.0
  http: ^0.12.0
  json_annotation: ^3.0.0

dev_dependencies:
  pedantic: ^1.8.0+1
  build_runner: ^1.7.2
  build_verify: ^1.1.1
  json_serializable: ^3.2.0
