name: aws_client.generator
description: Code generator for package:aws_client
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  archive: ^3.0.0
  args: ^2.2.0
  html: ^0.15.0
  http: ^0.13.3
  json_annotation: ^4.0.0
  path: ^1.7.0
  pool: ^1.4.0
  process_runner: ^4.0.0

dev_dependencies:
  pedantic: ^1.8.0+1
  build_runner: ^2.1.1
  build_verify: ^2.0.0
  json_serializable: ^5.0.0
  test: ^1.0.0
  version: ^2.0.0
  dart_style: ^2.0.0
  yaml: ^3.0.0