#   https://www.dartlang.org/guides/language/analysis-options
include: package:lints/recommended.yaml

analyzer:
  exclude: [generated/**]
  errors:
    deprecated_member_use_from_same_package: ignore
  language:
    strict-casts: true

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    annotate_overrides: true
    avoid_relative_lib_imports: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    collection_methods_unrelated_type: true
    directives_ordering: true
    empty_catches: true
    empty_statements: true
    hash_and_equals: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_leading_underscores_for_library_prefixes: false # Too many occurrences
    non_constant_identifier_names: true
    only_throw_errors: true
    overridden_fields: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    recursive_getters: true
    slash_for_doc_comments: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_statements: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_rethrow_when_possible: true
    use_super_parameters: false
    valid_regexps: true
