// AUTO-GENERATED: This file is generated by the `generator` package.
//
// Endpoint resolution conformance tests, derived from the service's
// `smithy.rules#endpointTests` trait.

// ignore_for_file: prefer_single_quotes, prefer_collection_literals, unnecessary_lambdas, unused_import

import 'package:aws_client/src/generated/cloud_front_key_value_store/v2022_07_26.endpoints.dart';
import 'package:aws_client/src/shared/src/protocol/endpoints/endpoint_resolver.dart';
import 'package:test/test.dart';

void main() {
  test('FIPS should error [0]', () {
    expect(
      () => resolveEndpoint(useFips: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: FIPS is not supported with CloudFront-KeyValueStore.')),
    );
  });
  test('KVS ARN must be provided to use this service [1]', () {
    expect(
      () => resolveEndpoint(),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'KVS ARN must be provided to use this service')),
    );
  });
  test('KVS ARN must be a valid ARN [2]', () {
    expect(
      () => resolveEndpoint(kvsARN: 'not-a-valid-arn'),
      throwsA(isA<EndpointResolutionException>()
          .having((e) => e.message, 'message', 'KVS ARN must be a valid ARN')),
    );
  });
  test(
      'Provided ARN was not a valid CloudFront Service ARN. Found: `notcloudfront` [3]',
      () {
    expect(
      () => resolveEndpoint(
          kvsARN:
              'arn:aws:notcloudfront::123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Provided ARN is not a valid CloudFront Service ARN. Found: `notcloudfront`')),
    );
  });
  test('Provided ARN must be a global resource ARN. Found: `us-west-2` [4]',
      () {
    expect(
      () => resolveEndpoint(
          kvsARN:
              'arn:aws:cloudfront:us-west-2:123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Provided ARN must be a global resource ARN. Found: `us-west-2`')),
    );
  });
  test(
      'ARN resource type is invalid. Expected `key-value-store`, found: `some-other-resource-type` [5]',
      () {
    expect(
      () => resolveEndpoint(
          kvsARN:
              'arn:aws:cloudfront::123456789012:some-other-resource-type/my-first-kvs-e10b1dce4f394248811e77167e0451ba'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'ARN resource type is invalid. Expected `key-value-store`, found: `some-other-resource-type`')),
    );
  });
  test('CloudFront-KeyValueStore is not supported in partition `aws-cn` [6]',
      () {
    expect(
      () => resolveEndpoint(
          kvsARN:
              'arn:aws-cn:cloudfront::123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'CloudFront-KeyValueStore is not supported in partition `aws-cn`')),
    );
  });
  test(
      'CloudFront-KeyValueStore is not supported in partition `aws-us-gov` [7]',
      () {
    expect(
      () => resolveEndpoint(
          kvsARN:
              'arn:aws-us-gov:cloudfront::123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'CloudFront-KeyValueStore is not supported in partition `aws-us-gov`')),
    );
  });
  test('Valid account based endpoint [8]', () {
    final resolved = resolveEndpoint(
        kvsARN:
            'arn:aws:cloudfront::123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba');
    expect(resolved.url, 'https://123456789012.cloudfront-kvs.global.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4a');
    expect(resolved.authSchemes[0].signingName, 'cloudfront-keyvaluestore');
    expect(resolved.authSchemes[0].signingRegion, isNull);
    expect(resolved.authSchemes[0].signingRegionSet, ['*']);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Valid account based endpoint, with SDK region [9]', () {
    final resolved = resolveEndpoint(
        kvsARN:
            'arn:aws:cloudfront::123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba',
        region: 'us-west-2');
    expect(resolved.url, 'https://123456789012.cloudfront-kvs.global.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4a');
    expect(resolved.authSchemes[0].signingName, 'cloudfront-keyvaluestore');
    expect(resolved.authSchemes[0].signingRegion, isNull);
    expect(resolved.authSchemes[0].signingRegionSet, ['*']);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Valid ARN, different partition, should error [10]', () {
    expect(
      () => resolveEndpoint(
          kvsARN:
              'arn:aws:cloudfront::123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba',
          region: 'cn-north-1'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Client was configured for partition `aws-cn` but Kvs ARN has `aws`')),
    );
  });
  test('Valid account based endpoint with FIPS, should error [11]', () {
    expect(
      () => resolveEndpoint(
          kvsARN:
              'arn:aws:cloudfront::123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba',
          region: 'us-east-1',
          useFips: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: FIPS is not supported with CloudFront-KeyValueStore.')),
    );
  });
  test('Custom sdk endpoint override [12]', () {
    final resolved = resolveEndpoint(
        kvsARN:
            'arn:aws:cloudfront::123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba',
        region: 'us-east-1',
        endpoint: 'https://my-override.example.com');
    expect(resolved.url, 'https://123456789012.my-override.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4a');
    expect(resolved.authSchemes[0].signingName, 'cloudfront-keyvaluestore');
    expect(resolved.authSchemes[0].signingRegion, isNull);
    expect(resolved.authSchemes[0].signingRegionSet, ['*']);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Custom sdk endpoint override with path and http [13]', () {
    final resolved = resolveEndpoint(
        kvsARN:
            'arn:aws:cloudfront::123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba',
        endpoint: 'http://my-override.example.com/custom-path');
    expect(resolved.url,
        'http://123456789012.my-override.example.com/custom-path');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4a');
    expect(resolved.authSchemes[0].signingName, 'cloudfront-keyvaluestore');
    expect(resolved.authSchemes[0].signingRegion, isNull);
    expect(resolved.authSchemes[0].signingRegionSet, ['*']);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Custom override with different partition should error [14]', () {
    expect(
      () => resolveEndpoint(
          kvsARN:
              'arn:aws:cloudfront::123456789012:key-value-store/my-first-kvs-e10b1dce4f394248811e77167e0451ba',
          region: 'us-gov-east-1',
          endpoint: 'https://my-override.example.com'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Client was configured for partition `aws-us-gov` but Kvs ARN has `aws`')),
    );
  });
}
