name: aws_credential_providers
description: |
  Credential provider utilities for resolving AWS credentials from different sources.
  Used with aws_xxx_api packages.
version: 0.0.2
homepage: https://github.com/agilord/aws_client/tree/master/aws_credential_providers

environment:
  sdk: '^3.0.0'

dependencies:
  aws_sts_api: ^1.2.0
  shared_aws_api: ^1.2.0

dev_dependencies:
  lints:
