import 'package:test/test.dart';
import 'awsJson1_0/empty_input_and_empty_output_test.dart' as _i0;
import 'awsJson1_0/endpoint_operation_test.dart' as _i1;
import 'awsJson1_0/endpoint_with_host_label_operation_test.dart' as _i2;
import 'awsJson1_0/host_with_path_operation_test.dart' as _i3;
import 'awsJson1_0/json_unions_test.dart' as _i4;
import 'awsJson1_0/no_input_and_no_output_test.dart' as _i5;
import 'awsJson1_0/no_input_and_output_test.dart' as _i6;
import 'awsJson1_0/operation_with_defaults_test.dart' as _i7;
import 'awsJson1_0/operation_with_required_members_test.dart' as _i8;
import 'awsJson1_0/operation_with_required_members_with_defaults_test.dart'
    as _i9;
import 'awsJson1_0/put_with_content_encoding_test.dart' as _i10;
import 'awsJson1_0/query_incompatible_operation_test.dart' as _i11;
import 'awsJson1_0/simple_scalar_properties_test.dart' as _i12;
import 'awsJson1_1/datetime_offsets_test.dart' as _i13;
import 'awsJson1_1/empty_operation_test.dart' as _i14;
import 'awsJson1_1/endpoint_operation_test.dart' as _i15;
import 'awsJson1_1/endpoint_with_host_label_operation_test.dart' as _i16;
import 'awsJson1_1/fractional_seconds_test.dart' as _i17;
import 'awsJson1_1/host_with_path_operation_test.dart' as _i18;
import 'awsJson1_1/json_enums_test.dart' as _i19;
import 'awsJson1_1/json_int_enums_test.dart' as _i20;
import 'awsJson1_1/json_unions_test.dart' as _i21;
import 'awsJson1_1/kitchen_sink_operation_test.dart' as _i22;
import 'awsJson1_1/null_operation_test.dart' as _i23;
import 'awsJson1_1/operation_with_optional_input_output_test.dart' as _i24;
import 'awsJson1_1/put_and_get_inline_documents_test.dart' as _i25;
import 'awsJson1_1/put_with_content_encoding_test.dart' as _i26;
import 'awsJson1_1/simple_scalar_properties_test.dart' as _i27;
import 'awsQuery/datetime_offsets_test.dart' as _i28;
import 'awsQuery/empty_input_and_empty_output_test.dart' as _i29;
import 'awsQuery/endpoint_operation_test.dart' as _i30;
import 'awsQuery/endpoint_with_host_label_operation_test.dart' as _i31;
import 'awsQuery/flattened_xml_map_test.dart' as _i32;
import 'awsQuery/flattened_xml_map_with_xml_name_test.dart' as _i33;
import 'awsQuery/flattened_xml_map_with_xml_namespace_test.dart' as _i34;
import 'awsQuery/fractional_seconds_test.dart' as _i35;
import 'awsQuery/greeting_with_errors_test.dart' as _i36;
import 'awsQuery/host_with_path_operation_test.dart' as _i37;
import 'awsQuery/ignores_wrapping_xml_name_test.dart' as _i38;
import 'awsQuery/nested_structures_test.dart' as _i39;
import 'awsQuery/no_input_and_no_output_test.dart' as _i40;
import 'awsQuery/no_input_and_output_test.dart' as _i41;
import 'awsQuery/put_with_content_encoding_test.dart' as _i42;
import 'awsQuery/query_idempotency_token_auto_fill_test.dart' as _i43;
import 'awsQuery/query_lists_test.dart' as _i44;
import 'awsQuery/query_maps_test.dart' as _i45;
import 'awsQuery/query_timestamps_test.dart' as _i46;
import 'awsQuery/recursive_xml_shapes_test.dart' as _i47;
import 'awsQuery/simple_input_params_test.dart' as _i48;
import 'awsQuery/simple_scalar_xml_properties_test.dart' as _i49;
import 'awsQuery/xml_blobs_test.dart' as _i50;
import 'awsQuery/xml_empty_blobs_test.dart' as _i51;
import 'awsQuery/xml_empty_lists_test.dart' as _i52;
import 'awsQuery/xml_empty_maps_test.dart' as _i53;
import 'awsQuery/xml_enums_test.dart' as _i54;
import 'awsQuery/xml_int_enums_test.dart' as _i55;
import 'awsQuery/xml_lists_test.dart' as _i56;
import 'awsQuery/xml_maps_test.dart' as _i57;
import 'awsQuery/xml_maps_xml_name_test.dart' as _i58;
import 'awsQuery/xml_namespaces_test.dart' as _i59;
import 'awsQuery/xml_timestamps_test.dart' as _i60;
import 'restJson1/constant_and_variable_query_string_test.dart' as _i61;
import 'restJson1/constant_query_string_test.dart' as _i62;
import 'restJson1/datetime_offsets_test.dart' as _i63;
import 'restJson1/document_type_as_map_value_test.dart' as _i64;
import 'restJson1/document_type_as_payload_test.dart' as _i65;
import 'restJson1/document_type_test.dart' as _i66;
import 'restJson1/empty_input_and_empty_output_test.dart' as _i67;
import 'restJson1/endpoint_operation_test.dart' as _i68;
import 'restJson1/endpoint_with_host_label_operation_test.dart' as _i69;
import 'restJson1/fractional_seconds_test.dart' as _i70;
import 'restJson1/greeting_with_errors_test.dart' as _i71;
import 'restJson1/host_with_path_operation_test.dart' as _i72;
import 'restJson1/http_checksum_required_test.dart' as _i73;
import 'restJson1/http_empty_prefix_headers_test.dart' as _i74;
import 'restJson1/http_enum_payload_test.dart' as _i75;
import 'restJson1/http_payload_traits_test.dart' as _i76;
import 'restJson1/http_payload_traits_with_media_type_test.dart' as _i77;
import 'restJson1/http_payload_with_structure_test.dart' as _i78;
import 'restJson1/http_payload_with_union_test.dart' as _i79;
import 'restJson1/http_prefix_headers_in_response_test.dart' as _i80;
import 'restJson1/http_prefix_headers_test.dart' as _i81;
import 'restJson1/http_query_params_only_operation_test.dart' as _i82;
import 'restJson1/http_request_with_float_labels_test.dart' as _i83;
import 'restJson1/http_request_with_greedy_label_in_path_test.dart' as _i84;
import 'restJson1/http_request_with_labels_and_timestamp_format_test.dart'
    as _i85;
import 'restJson1/http_request_with_regex_literal_test.dart' as _i86;
import 'restJson1/http_response_code_test.dart' as _i87;
import 'restJson1/http_string_payload_test.dart' as _i88;
import 'restJson1/ignore_query_params_in_response_test.dart' as _i89;
import 'restJson1/input_and_output_with_headers_test.dart' as _i90;
import 'restJson1/json_blobs_test.dart' as _i91;
import 'restJson1/json_enums_test.dart' as _i92;
import 'restJson1/json_int_enums_test.dart' as _i93;
import 'restJson1/json_lists_test.dart' as _i94;
import 'restJson1/json_maps_test.dart' as _i95;
import 'restJson1/json_timestamps_test.dart' as _i96;
import 'restJson1/json_unions_test.dart' as _i97;
import 'restJson1/media_type_header_test.dart' as _i98;
import 'restJson1/no_input_and_no_output_test.dart' as _i99;
import 'restJson1/no_input_and_output_test.dart' as _i100;
import 'restJson1/null_and_empty_headers_client_test.dart' as _i101;
import 'restJson1/omits_null_serializes_empty_string_test.dart' as _i102;
import 'restJson1/omits_serializing_empty_lists_test.dart' as _i103;
import 'restJson1/operation_with_defaults_test.dart' as _i104;
import 'restJson1/post_player_action_test.dart' as _i105;
import 'restJson1/post_union_with_json_name_test.dart' as _i106;
import 'restJson1/put_with_content_encoding_test.dart' as _i107;
import 'restJson1/query_idempotency_token_auto_fill_test.dart' as _i108;
import 'restJson1/query_params_as_string_list_map_test.dart' as _i109;
import 'restJson1/query_precedence_test.dart' as _i110;
import 'restJson1/recursive_shapes_test.dart' as _i111;
import 'restJson1/simple_scalar_properties_test.dart' as _i112;
import 'restJson1/sparse_json_lists_test.dart' as _i113;
import 'restJson1/streaming_traits_require_length_test.dart' as _i114;
import 'restJson1/streaming_traits_test.dart' as _i115;
import 'restJson1/streaming_traits_with_media_type_test.dart' as _i116;
import 'restJson1/test_body_structure_test.dart' as _i117;
import 'restJson1/test_get_no_input_no_payload_test.dart' as _i118;
import 'restJson1/test_get_no_payload_test.dart' as _i119;
import 'restJson1/test_payload_blob_test.dart' as _i120;
import 'restJson1/test_payload_structure_test.dart' as _i121;
import 'restJson1/test_post_no_input_no_payload_test.dart' as _i122;
import 'restJson1/test_post_no_payload_test.dart' as _i123;
import 'restJson1/timestamp_format_headers_test.dart' as _i124;
import 'restJson1/unit_input_and_output_test.dart' as _i125;
import 'restXml/body_with_xml_name_test.dart' as _i126;
import 'restXml/constant_and_variable_query_string_test.dart' as _i127;
import 'restXml/constant_query_string_test.dart' as _i128;
import 'restXml/datetime_offsets_test.dart' as _i129;
import 'restXml/empty_input_and_empty_output_test.dart' as _i130;
import 'restXml/endpoint_operation_test.dart' as _i131;
import 'restXml/endpoint_with_host_label_header_operation_test.dart' as _i132;
import 'restXml/endpoint_with_host_label_operation_test.dart' as _i133;
import 'restXml/flattened_xml_map_test.dart' as _i134;
import 'restXml/flattened_xml_map_with_xml_name_test.dart' as _i135;
import 'restXml/flattened_xml_map_with_xml_namespace_test.dart' as _i136;
import 'restXml/fractional_seconds_test.dart' as _i137;
import 'restXml/greeting_with_errors_test.dart' as _i138;
import 'restXml/http_empty_prefix_headers_test.dart' as _i139;
import 'restXml/http_enum_payload_test.dart' as _i140;
import 'restXml/http_payload_traits_test.dart' as _i141;
import 'restXml/http_payload_traits_with_media_type_test.dart' as _i142;
import 'restXml/http_payload_with_member_xml_name_test.dart' as _i143;
import 'restXml/http_payload_with_structure_test.dart' as _i144;
import 'restXml/http_payload_with_union_test.dart' as _i145;
import 'restXml/http_payload_with_xml_name_test.dart' as _i146;
import 'restXml/http_payload_with_xml_namespace_and_prefix_test.dart' as _i147;
import 'restXml/http_payload_with_xml_namespace_test.dart' as _i148;
import 'restXml/http_prefix_headers_test.dart' as _i149;
import 'restXml/http_request_with_float_labels_test.dart' as _i150;
import 'restXml/http_request_with_greedy_label_in_path_test.dart' as _i151;
import 'restXml/http_request_with_labels_and_timestamp_format_test.dart'
    as _i152;
import 'restXml/http_response_code_test.dart' as _i153;
import 'restXml/http_string_payload_test.dart' as _i154;
import 'restXml/ignore_query_params_in_response_test.dart' as _i155;
import 'restXml/input_and_output_with_headers_test.dart' as _i156;
import 'restXml/nested_xml_map_with_xml_name_test.dart' as _i157;
import 'restXml/nested_xml_maps_test.dart' as _i158;
import 'restXml/no_input_and_no_output_test.dart' as _i159;
import 'restXml/no_input_and_output_test.dart' as _i160;
import 'restXml/null_and_empty_headers_client_test.dart' as _i161;
import 'restXml/omits_null_serializes_empty_string_test.dart' as _i162;
import 'restXml/put_with_content_encoding_test.dart' as _i163;
import 'restXml/query_idempotency_token_auto_fill_test.dart' as _i164;
import 'restXml/query_params_as_string_list_map_test.dart' as _i165;
import 'restXml/query_precedence_test.dart' as _i166;
import 'restXml/recursive_shapes_test.dart' as _i167;
import 'restXml/simple_scalar_properties_test.dart' as _i168;
import 'restXml/timestamp_format_headers_test.dart' as _i169;
import 'restXml/xml_attributes_in_middle_test.dart' as _i170;
import 'restXml/xml_attributes_on_payload_test.dart' as _i171;
import 'restXml/xml_attributes_test.dart' as _i172;
import 'restXml/xml_blobs_test.dart' as _i173;
import 'restXml/xml_empty_blobs_test.dart' as _i174;
import 'restXml/xml_empty_lists_test.dart' as _i175;
import 'restXml/xml_empty_maps_test.dart' as _i176;
import 'restXml/xml_empty_strings_test.dart' as _i177;
import 'restXml/xml_enums_test.dart' as _i178;
import 'restXml/xml_int_enums_test.dart' as _i179;
import 'restXml/xml_lists_test.dart' as _i180;
import 'restXml/xml_map_with_xml_namespace_test.dart' as _i181;
import 'restXml/xml_maps_test.dart' as _i182;
import 'restXml/xml_maps_xml_name_test.dart' as _i183;
import 'restXml/xml_namespaces_test.dart' as _i184;
import 'restXml/xml_timestamps_test.dart' as _i185;
import 'restXml/xml_unions_test.dart' as _i186;

void main() {
  group('awsJson1_0/empty_input_and_empty_output_test', _i0.main);
  group('awsJson1_0/endpoint_operation_test', _i1.main);
  group('awsJson1_0/endpoint_with_host_label_operation_test', _i2.main);
  group('awsJson1_0/host_with_path_operation_test', _i3.main);
  group('awsJson1_0/json_unions_test', _i4.main);
  group('awsJson1_0/no_input_and_no_output_test', _i5.main);
  group('awsJson1_0/no_input_and_output_test', _i6.main);
  group('awsJson1_0/operation_with_defaults_test', _i7.main);
  group('awsJson1_0/operation_with_required_members_test', _i8.main);
  group('awsJson1_0/operation_with_required_members_with_defaults_test',
      _i9.main);
  group('awsJson1_0/put_with_content_encoding_test', _i10.main);
  group('awsJson1_0/query_incompatible_operation_test', _i11.main);
  group('awsJson1_0/simple_scalar_properties_test', _i12.main);
  group('awsJson1_1/datetime_offsets_test', _i13.main);
  group('awsJson1_1/empty_operation_test', _i14.main);
  group('awsJson1_1/endpoint_operation_test', _i15.main);
  group('awsJson1_1/endpoint_with_host_label_operation_test', _i16.main);
  group('awsJson1_1/fractional_seconds_test', _i17.main);
  group('awsJson1_1/host_with_path_operation_test', _i18.main);
  group('awsJson1_1/json_enums_test', _i19.main);
  group('awsJson1_1/json_int_enums_test', _i20.main);
  group('awsJson1_1/json_unions_test', _i21.main);
  group('awsJson1_1/kitchen_sink_operation_test', _i22.main);
  group('awsJson1_1/null_operation_test', _i23.main);
  group('awsJson1_1/operation_with_optional_input_output_test', _i24.main);
  group('awsJson1_1/put_and_get_inline_documents_test', _i25.main);
  group('awsJson1_1/put_with_content_encoding_test', _i26.main);
  group('awsJson1_1/simple_scalar_properties_test', _i27.main);
  group('awsQuery/datetime_offsets_test', _i28.main);
  group('awsQuery/empty_input_and_empty_output_test', _i29.main);
  group('awsQuery/endpoint_operation_test', _i30.main);
  group('awsQuery/endpoint_with_host_label_operation_test', _i31.main);
  group('awsQuery/flattened_xml_map_test', _i32.main);
  group('awsQuery/flattened_xml_map_with_xml_name_test', _i33.main);
  group('awsQuery/flattened_xml_map_with_xml_namespace_test', _i34.main);
  group('awsQuery/fractional_seconds_test', _i35.main);
  group('awsQuery/greeting_with_errors_test', _i36.main);
  group('awsQuery/host_with_path_operation_test', _i37.main);
  group('awsQuery/ignores_wrapping_xml_name_test', _i38.main);
  group('awsQuery/nested_structures_test', _i39.main);
  group('awsQuery/no_input_and_no_output_test', _i40.main);
  group('awsQuery/no_input_and_output_test', _i41.main);
  group('awsQuery/put_with_content_encoding_test', _i42.main);
  group('awsQuery/query_idempotency_token_auto_fill_test', _i43.main);
  group('awsQuery/query_lists_test', _i44.main);
  group('awsQuery/query_maps_test', _i45.main);
  group('awsQuery/query_timestamps_test', _i46.main);
  group('awsQuery/recursive_xml_shapes_test', _i47.main);
  group('awsQuery/simple_input_params_test', _i48.main);
  group('awsQuery/simple_scalar_xml_properties_test', _i49.main);
  group('awsQuery/xml_blobs_test', _i50.main);
  group('awsQuery/xml_empty_blobs_test', _i51.main);
  group('awsQuery/xml_empty_lists_test', _i52.main);
  group('awsQuery/xml_empty_maps_test', _i53.main);
  group('awsQuery/xml_enums_test', _i54.main);
  group('awsQuery/xml_int_enums_test', _i55.main);
  group('awsQuery/xml_lists_test', _i56.main);
  group('awsQuery/xml_maps_test', _i57.main);
  group('awsQuery/xml_maps_xml_name_test', _i58.main);
  group('awsQuery/xml_namespaces_test', _i59.main);
  group('awsQuery/xml_timestamps_test', _i60.main);
  group('restJson1/constant_and_variable_query_string_test', _i61.main);
  group('restJson1/constant_query_string_test', _i62.main);
  group('restJson1/datetime_offsets_test', _i63.main);
  group('restJson1/document_type_as_map_value_test', _i64.main);
  group('restJson1/document_type_as_payload_test', _i65.main);
  group('restJson1/document_type_test', _i66.main);
  group('restJson1/empty_input_and_empty_output_test', _i67.main);
  group('restJson1/endpoint_operation_test', _i68.main);
  group('restJson1/endpoint_with_host_label_operation_test', _i69.main);
  group('restJson1/fractional_seconds_test', _i70.main);
  group('restJson1/greeting_with_errors_test', _i71.main);
  group('restJson1/host_with_path_operation_test', _i72.main);
  group('restJson1/http_checksum_required_test', _i73.main);
  group('restJson1/http_empty_prefix_headers_test', _i74.main);
  group('restJson1/http_enum_payload_test', _i75.main);
  group('restJson1/http_payload_traits_test', _i76.main);
  group('restJson1/http_payload_traits_with_media_type_test', _i77.main);
  group('restJson1/http_payload_with_structure_test', _i78.main);
  group('restJson1/http_payload_with_union_test', _i79.main);
  group('restJson1/http_prefix_headers_in_response_test', _i80.main);
  group('restJson1/http_prefix_headers_test', _i81.main);
  group('restJson1/http_query_params_only_operation_test', _i82.main);
  group('restJson1/http_request_with_float_labels_test', _i83.main);
  group('restJson1/http_request_with_greedy_label_in_path_test', _i84.main);
  group('restJson1/http_request_with_labels_and_timestamp_format_test',
      _i85.main);
  group('restJson1/http_request_with_regex_literal_test', _i86.main);
  group('restJson1/http_response_code_test', _i87.main);
  group('restJson1/http_string_payload_test', _i88.main);
  group('restJson1/ignore_query_params_in_response_test', _i89.main);
  group('restJson1/input_and_output_with_headers_test', _i90.main);
  group('restJson1/json_blobs_test', _i91.main);
  group('restJson1/json_enums_test', _i92.main);
  group('restJson1/json_int_enums_test', _i93.main);
  group('restJson1/json_lists_test', _i94.main);
  group('restJson1/json_maps_test', _i95.main);
  group('restJson1/json_timestamps_test', _i96.main);
  group('restJson1/json_unions_test', _i97.main);
  group('restJson1/media_type_header_test', _i98.main);
  group('restJson1/no_input_and_no_output_test', _i99.main);
  group('restJson1/no_input_and_output_test', _i100.main);
  group('restJson1/null_and_empty_headers_client_test', _i101.main);
  group('restJson1/omits_null_serializes_empty_string_test', _i102.main);
  group('restJson1/omits_serializing_empty_lists_test', _i103.main);
  group('restJson1/operation_with_defaults_test', _i104.main);
  group('restJson1/post_player_action_test', _i105.main);
  group('restJson1/post_union_with_json_name_test', _i106.main);
  group('restJson1/put_with_content_encoding_test', _i107.main);
  group('restJson1/query_idempotency_token_auto_fill_test', _i108.main);
  group('restJson1/query_params_as_string_list_map_test', _i109.main);
  group('restJson1/query_precedence_test', _i110.main);
  group('restJson1/recursive_shapes_test', _i111.main);
  group('restJson1/simple_scalar_properties_test', _i112.main);
  group('restJson1/sparse_json_lists_test', _i113.main);
  group('restJson1/streaming_traits_require_length_test', _i114.main);
  group('restJson1/streaming_traits_test', _i115.main);
  group('restJson1/streaming_traits_with_media_type_test', _i116.main);
  group('restJson1/test_body_structure_test', _i117.main);
  group('restJson1/test_get_no_input_no_payload_test', _i118.main);
  group('restJson1/test_get_no_payload_test', _i119.main);
  group('restJson1/test_payload_blob_test', _i120.main);
  group('restJson1/test_payload_structure_test', _i121.main);
  group('restJson1/test_post_no_input_no_payload_test', _i122.main);
  group('restJson1/test_post_no_payload_test', _i123.main);
  group('restJson1/timestamp_format_headers_test', _i124.main);
  group('restJson1/unit_input_and_output_test', _i125.main);
  group('restXml/body_with_xml_name_test', _i126.main);
  group('restXml/constant_and_variable_query_string_test', _i127.main);
  group('restXml/constant_query_string_test', _i128.main);
  group('restXml/datetime_offsets_test', _i129.main);
  group('restXml/empty_input_and_empty_output_test', _i130.main);
  group('restXml/endpoint_operation_test', _i131.main);
  group('restXml/endpoint_with_host_label_header_operation_test', _i132.main);
  group('restXml/endpoint_with_host_label_operation_test', _i133.main);
  group('restXml/flattened_xml_map_test', _i134.main);
  group('restXml/flattened_xml_map_with_xml_name_test', _i135.main);
  group('restXml/flattened_xml_map_with_xml_namespace_test', _i136.main);
  group('restXml/fractional_seconds_test', _i137.main);
  group('restXml/greeting_with_errors_test', _i138.main);
  group('restXml/http_empty_prefix_headers_test', _i139.main);
  group('restXml/http_enum_payload_test', _i140.main);
  group('restXml/http_payload_traits_test', _i141.main);
  group('restXml/http_payload_traits_with_media_type_test', _i142.main);
  group('restXml/http_payload_with_member_xml_name_test', _i143.main);
  group('restXml/http_payload_with_structure_test', _i144.main);
  group('restXml/http_payload_with_union_test', _i145.main);
  group('restXml/http_payload_with_xml_name_test', _i146.main);
  group('restXml/http_payload_with_xml_namespace_and_prefix_test', _i147.main);
  group('restXml/http_payload_with_xml_namespace_test', _i148.main);
  group('restXml/http_prefix_headers_test', _i149.main);
  group('restXml/http_request_with_float_labels_test', _i150.main);
  group('restXml/http_request_with_greedy_label_in_path_test', _i151.main);
  group(
      'restXml/http_request_with_labels_and_timestamp_format_test', _i152.main);
  group('restXml/http_response_code_test', _i153.main);
  group('restXml/http_string_payload_test', _i154.main);
  group('restXml/ignore_query_params_in_response_test', _i155.main);
  group('restXml/input_and_output_with_headers_test', _i156.main);
  group('restXml/nested_xml_map_with_xml_name_test', _i157.main);
  group('restXml/nested_xml_maps_test', _i158.main);
  group('restXml/no_input_and_no_output_test', _i159.main);
  group('restXml/no_input_and_output_test', _i160.main);
  group('restXml/null_and_empty_headers_client_test', _i161.main);
  group('restXml/omits_null_serializes_empty_string_test', _i162.main);
  group('restXml/put_with_content_encoding_test', _i163.main);
  group('restXml/query_idempotency_token_auto_fill_test', _i164.main);
  group('restXml/query_params_as_string_list_map_test', _i165.main);
  group('restXml/query_precedence_test', _i166.main);
  group('restXml/recursive_shapes_test', _i167.main);
  group('restXml/simple_scalar_properties_test', _i168.main);
  group('restXml/timestamp_format_headers_test', _i169.main);
  group('restXml/xml_attributes_in_middle_test', _i170.main);
  group('restXml/xml_attributes_on_payload_test', _i171.main);
  group('restXml/xml_attributes_test', _i172.main);
  group('restXml/xml_blobs_test', _i173.main);
  group('restXml/xml_empty_blobs_test', _i174.main);
  group('restXml/xml_empty_lists_test', _i175.main);
  group('restXml/xml_empty_maps_test', _i176.main);
  group('restXml/xml_empty_strings_test', _i177.main);
  group('restXml/xml_enums_test', _i178.main);
  group('restXml/xml_int_enums_test', _i179.main);
  group('restXml/xml_lists_test', _i180.main);
  group('restXml/xml_map_with_xml_namespace_test', _i181.main);
  group('restXml/xml_maps_test', _i182.main);
  group('restXml/xml_maps_xml_name_test', _i183.main);
  group('restXml/xml_namespaces_test', _i184.main);
  group('restXml/xml_timestamps_test', _i185.main);
  group('restXml/xml_unions_test', _i186.main);
}
