import 'package:test/test.dart';
import 'awsJson1_0/ContentTypeParameters_test.dart' as _i0;
import 'awsJson1_0/EmptyInputAndEmptyOutput_test.dart' as _i1;
import 'awsJson1_0/EndpointOperation_test.dart' as _i2;
import 'awsJson1_0/EndpointWithHostLabelOperation_test.dart' as _i3;
import 'awsJson1_0/HostWithPathOperation_test.dart' as _i4;
import 'awsJson1_0/JsonUnions_test.dart' as _i5;
import 'awsJson1_0/NoInputAndNoOutput_test.dart' as _i6;
import 'awsJson1_0/NoInputAndOutput_test.dart' as _i7;
import 'awsJson1_0/OperationWithDefaults_test.dart' as _i8;
import 'awsJson1_0/OperationWithRequiredMembersWithDefaults_test.dart' as _i9;
import 'awsJson1_0/OperationWithRequiredMembers_test.dart' as _i10;
import 'awsJson1_0/PutWithContentEncoding_test.dart' as _i11;
import 'awsJson1_0/QueryIncompatibleOperation_test.dart' as _i12;
import 'awsJson1_0/SimpleScalarProperties_test.dart' as _i13;
import 'awsJson1_1/ContentTypeParameters_test.dart' as _i14;
import 'awsJson1_1/DatetimeOffsets_test.dart' as _i15;
import 'awsJson1_1/EmptyOperation_test.dart' as _i16;
import 'awsJson1_1/EndpointOperation_test.dart' as _i17;
import 'awsJson1_1/EndpointWithHostLabelOperation_test.dart' as _i18;
import 'awsJson1_1/FractionalSeconds_test.dart' as _i19;
import 'awsJson1_1/HostWithPathOperation_test.dart' as _i20;
import 'awsJson1_1/JsonEnums_test.dart' as _i21;
import 'awsJson1_1/JsonIntEnums_test.dart' as _i22;
import 'awsJson1_1/JsonUnions_test.dart' as _i23;
import 'awsJson1_1/KitchenSinkOperation_test.dart' as _i24;
import 'awsJson1_1/NullOperation_test.dart' as _i25;
import 'awsJson1_1/OperationWithOptionalInputOutput_test.dart' as _i26;
import 'awsJson1_1/PutAndGetInlineDocuments_test.dart' as _i27;
import 'awsJson1_1/PutWithContentEncoding_test.dart' as _i28;
import 'awsJson1_1/SimpleScalarProperties_test.dart' as _i29;
import 'awsQuery/DatetimeOffsets_test.dart' as _i30;
import 'awsQuery/EmptyInputAndEmptyOutput_test.dart' as _i31;
import 'awsQuery/EndpointOperation_test.dart' as _i32;
import 'awsQuery/EndpointWithHostLabelOperation_test.dart' as _i33;
import 'awsQuery/FlattenedXmlMapWithXmlName_test.dart' as _i34;
import 'awsQuery/FlattenedXmlMapWithXmlNamespace_test.dart' as _i35;
import 'awsQuery/FlattenedXmlMap_test.dart' as _i36;
import 'awsQuery/FractionalSeconds_test.dart' as _i37;
import 'awsQuery/GreetingWithErrors_test.dart' as _i38;
import 'awsQuery/HostWithPathOperation_test.dart' as _i39;
import 'awsQuery/IgnoresWrappingXmlName_test.dart' as _i40;
import 'awsQuery/NestedStructures_test.dart' as _i41;
import 'awsQuery/NoInputAndNoOutput_test.dart' as _i42;
import 'awsQuery/NoInputAndOutput_test.dart' as _i43;
import 'awsQuery/PutWithContentEncoding_test.dart' as _i44;
import 'awsQuery/QueryIdempotencyTokenAutoFill_test.dart' as _i45;
import 'awsQuery/QueryLists_test.dart' as _i46;
import 'awsQuery/QueryMaps_test.dart' as _i47;
import 'awsQuery/QueryTimestamps_test.dart' as _i48;
import 'awsQuery/RecursiveXmlShapes_test.dart' as _i49;
import 'awsQuery/SimpleInputParams_test.dart' as _i50;
import 'awsQuery/SimpleScalarXmlProperties_test.dart' as _i51;
import 'awsQuery/XmlBlobs_test.dart' as _i52;
import 'awsQuery/XmlEmptyBlobs_test.dart' as _i53;
import 'awsQuery/XmlEmptyLists_test.dart' as _i54;
import 'awsQuery/XmlEmptyMaps_test.dart' as _i55;
import 'awsQuery/XmlEnums_test.dart' as _i56;
import 'awsQuery/XmlIntEnums_test.dart' as _i57;
import 'awsQuery/XmlLists_test.dart' as _i58;
import 'awsQuery/XmlMapsXmlName_test.dart' as _i59;
import 'awsQuery/XmlMaps_test.dart' as _i60;
import 'awsQuery/XmlNamespaces_test.dart' as _i61;
import 'awsQuery/XmlTimestamps_test.dart' as _i62;
import 'restJson1/ConstantAndVariableQueryString_test.dart' as _i63;
import 'restJson1/ConstantQueryString_test.dart' as _i64;
import 'restJson1/ContentTypeParameters_test.dart' as _i65;
import 'restJson1/DatetimeOffsets_test.dart' as _i66;
import 'restJson1/DocumentTypeAsMapValue_test.dart' as _i67;
import 'restJson1/DocumentTypeAsPayload_test.dart' as _i68;
import 'restJson1/DocumentType_test.dart' as _i69;
import 'restJson1/EmptyInputAndEmptyOutput_test.dart' as _i70;
import 'restJson1/EndpointOperation_test.dart' as _i71;
import 'restJson1/EndpointWithHostLabelOperation_test.dart' as _i72;
import 'restJson1/FractionalSeconds_test.dart' as _i73;
import 'restJson1/GreetingWithErrors_test.dart' as _i74;
import 'restJson1/HostWithPathOperation_test.dart' as _i75;
import 'restJson1/HttpChecksumRequired_test.dart' as _i76;
import 'restJson1/HttpEmptyPrefixHeaders_test.dart' as _i77;
import 'restJson1/HttpEnumPayload_test.dart' as _i78;
import 'restJson1/HttpPayloadTraitsWithMediaType_test.dart' as _i79;
import 'restJson1/HttpPayloadTraits_test.dart' as _i80;
import 'restJson1/HttpPayloadWithStructure_test.dart' as _i81;
import 'restJson1/HttpPayloadWithUnion_test.dart' as _i82;
import 'restJson1/HttpPrefixHeadersInResponse_test.dart' as _i83;
import 'restJson1/HttpPrefixHeaders_test.dart' as _i84;
import 'restJson1/HttpQueryParamsOnlyOperation_test.dart' as _i85;
import 'restJson1/HttpRequestWithFloatLabels_test.dart' as _i86;
import 'restJson1/HttpRequestWithGreedyLabelInPath_test.dart' as _i87;
import 'restJson1/HttpRequestWithLabelsAndTimestampFormat_test.dart' as _i88;
import 'restJson1/HttpRequestWithRegexLiteral_test.dart' as _i89;
import 'restJson1/HttpResponseCode_test.dart' as _i90;
import 'restJson1/HttpStringPayload_test.dart' as _i91;
import 'restJson1/IgnoreQueryParamsInResponse_test.dart' as _i92;
import 'restJson1/InputAndOutputWithHeaders_test.dart' as _i93;
import 'restJson1/JsonBlobs_test.dart' as _i94;
import 'restJson1/JsonEnums_test.dart' as _i95;
import 'restJson1/JsonIntEnums_test.dart' as _i96;
import 'restJson1/JsonLists_test.dart' as _i97;
import 'restJson1/JsonMaps_test.dart' as _i98;
import 'restJson1/JsonTimestamps_test.dart' as _i99;
import 'restJson1/JsonUnions_test.dart' as _i100;
import 'restJson1/MediaTypeHeader_test.dart' as _i101;
import 'restJson1/NoInputAndNoOutput_test.dart' as _i102;
import 'restJson1/NoInputAndOutput_test.dart' as _i103;
import 'restJson1/NullAndEmptyHeadersClient_test.dart' as _i104;
import 'restJson1/NullAndEmptyHeadersServer_test.dart' as _i105;
import 'restJson1/OmitsNullSerializesEmptyString_test.dart' as _i106;
import 'restJson1/OmitsSerializingEmptyLists_test.dart' as _i107;
import 'restJson1/OperationWithDefaults_test.dart' as _i108;
import 'restJson1/PostPlayerAction_test.dart' as _i109;
import 'restJson1/PostUnionWithJsonName_test.dart' as _i110;
import 'restJson1/PutWithContentEncoding_test.dart' as _i111;
import 'restJson1/QueryIdempotencyTokenAutoFill_test.dart' as _i112;
import 'restJson1/QueryParamsAsStringListMap_test.dart' as _i113;
import 'restJson1/QueryPrecedence_test.dart' as _i114;
import 'restJson1/RecursiveShapes_test.dart' as _i115;
import 'restJson1/ResponseCodeHttpFallback_test.dart' as _i116;
import 'restJson1/ResponseCodeRequired_test.dart' as _i117;
import 'restJson1/SimpleScalarProperties_test.dart' as _i118;
import 'restJson1/SparseJsonLists_test.dart' as _i119;
import 'restJson1/StreamingTraitsRequireLength_test.dart' as _i120;
import 'restJson1/StreamingTraitsWithMediaType_test.dart' as _i121;
import 'restJson1/StreamingTraits_test.dart' as _i122;
import 'restJson1/TestBodyStructure_test.dart' as _i123;
import 'restJson1/TestGetNoInputNoPayload_test.dart' as _i124;
import 'restJson1/TestGetNoPayload_test.dart' as _i125;
import 'restJson1/TestPayloadBlob_test.dart' as _i126;
import 'restJson1/TestPayloadStructure_test.dart' as _i127;
import 'restJson1/TestPostNoInputNoPayload_test.dart' as _i128;
import 'restJson1/TestPostNoPayload_test.dart' as _i129;
import 'restJson1/TimestampFormatHeaders_test.dart' as _i130;
import 'restJson1/UnitInputAndOutput_test.dart' as _i131;
import 'restXml/BodyWithXmlName_test.dart' as _i132;
import 'restXml/ConstantAndVariableQueryString_test.dart' as _i133;
import 'restXml/ConstantQueryString_test.dart' as _i134;
import 'restXml/ContentTypeParameters_test.dart' as _i135;
import 'restXml/DatetimeOffsets_test.dart' as _i136;
import 'restXml/EmptyInputAndEmptyOutput_test.dart' as _i137;
import 'restXml/EndpointOperation_test.dart' as _i138;
import 'restXml/EndpointWithHostLabelHeaderOperation_test.dart' as _i139;
import 'restXml/EndpointWithHostLabelOperation_test.dart' as _i140;
import 'restXml/FlattenedXmlMapWithXmlName_test.dart' as _i141;
import 'restXml/FlattenedXmlMapWithXmlNamespace_test.dart' as _i142;
import 'restXml/FlattenedXmlMap_test.dart' as _i143;
import 'restXml/FractionalSeconds_test.dart' as _i144;
import 'restXml/GreetingWithErrors_test.dart' as _i145;
import 'restXml/HttpEmptyPrefixHeaders_test.dart' as _i146;
import 'restXml/HttpEnumPayload_test.dart' as _i147;
import 'restXml/HttpPayloadTraitsWithMediaType_test.dart' as _i148;
import 'restXml/HttpPayloadTraits_test.dart' as _i149;
import 'restXml/HttpPayloadWithMemberXmlName_test.dart' as _i150;
import 'restXml/HttpPayloadWithStructure_test.dart' as _i151;
import 'restXml/HttpPayloadWithUnion_test.dart' as _i152;
import 'restXml/HttpPayloadWithXmlName_test.dart' as _i153;
import 'restXml/HttpPayloadWithXmlNamespaceAndPrefix_test.dart' as _i154;
import 'restXml/HttpPayloadWithXmlNamespace_test.dart' as _i155;
import 'restXml/HttpPrefixHeaders_test.dart' as _i156;
import 'restXml/HttpRequestWithFloatLabels_test.dart' as _i157;
import 'restXml/HttpRequestWithGreedyLabelInPath_test.dart' as _i158;
import 'restXml/HttpRequestWithLabelsAndTimestampFormat_test.dart' as _i159;
import 'restXml/HttpResponseCode_test.dart' as _i160;
import 'restXml/HttpStringPayload_test.dart' as _i161;
import 'restXml/IgnoreQueryParamsInResponse_test.dart' as _i162;
import 'restXml/InputAndOutputWithHeaders_test.dart' as _i163;
import 'restXml/NestedXmlMapWithXmlName_test.dart' as _i164;
import 'restXml/NestedXmlMaps_test.dart' as _i165;
import 'restXml/NoInputAndNoOutput_test.dart' as _i166;
import 'restXml/NoInputAndOutput_test.dart' as _i167;
import 'restXml/NullAndEmptyHeadersClient_test.dart' as _i168;
import 'restXml/NullAndEmptyHeadersServer_test.dart' as _i169;
import 'restXml/OmitsNullSerializesEmptyString_test.dart' as _i170;
import 'restXml/PutWithContentEncoding_test.dart' as _i171;
import 'restXml/QueryIdempotencyTokenAutoFill_test.dart' as _i172;
import 'restXml/QueryParamsAsStringListMap_test.dart' as _i173;
import 'restXml/QueryPrecedence_test.dart' as _i174;
import 'restXml/RecursiveShapes_test.dart' as _i175;
import 'restXml/SimpleScalarProperties_test.dart' as _i176;
import 'restXml/TimestampFormatHeaders_test.dart' as _i177;
import 'restXml/XmlAttributesInMiddle_test.dart' as _i178;
import 'restXml/XmlAttributesOnPayload_test.dart' as _i179;
import 'restXml/XmlAttributes_test.dart' as _i180;
import 'restXml/XmlBlobs_test.dart' as _i181;
import 'restXml/XmlEmptyBlobs_test.dart' as _i182;
import 'restXml/XmlEmptyLists_test.dart' as _i183;
import 'restXml/XmlEmptyMaps_test.dart' as _i184;
import 'restXml/XmlEmptyStrings_test.dart' as _i185;
import 'restXml/XmlEnums_test.dart' as _i186;
import 'restXml/XmlIntEnums_test.dart' as _i187;
import 'restXml/XmlLists_test.dart' as _i188;
import 'restXml/XmlMapWithXmlNamespace_test.dart' as _i189;
import 'restXml/XmlMapsXmlName_test.dart' as _i190;
import 'restXml/XmlMaps_test.dart' as _i191;
import 'restXml/XmlNamespaces_test.dart' as _i192;
import 'restXml/XmlTimestamps_test.dart' as _i193;
import 'restXml/XmlUnions_test.dart' as _i194;

void main() {
  group('awsJson1_0/ContentTypeParameters_test', _i0.main);
  group('awsJson1_0/EmptyInputAndEmptyOutput_test', _i1.main);
  group('awsJson1_0/EndpointOperation_test', _i2.main);
  group('awsJson1_0/EndpointWithHostLabelOperation_test', _i3.main);
  group('awsJson1_0/HostWithPathOperation_test', _i4.main);
  group('awsJson1_0/JsonUnions_test', _i5.main);
  group('awsJson1_0/NoInputAndNoOutput_test', _i6.main);
  group('awsJson1_0/NoInputAndOutput_test', _i7.main);
  group('awsJson1_0/OperationWithDefaults_test', _i8.main);
  group('awsJson1_0/OperationWithRequiredMembersWithDefaults_test', _i9.main);
  group('awsJson1_0/OperationWithRequiredMembers_test', _i10.main);
  group('awsJson1_0/PutWithContentEncoding_test', _i11.main);
  group('awsJson1_0/QueryIncompatibleOperation_test', _i12.main);
  group('awsJson1_0/SimpleScalarProperties_test', _i13.main);
  group('awsJson1_1/ContentTypeParameters_test', _i14.main);
  group('awsJson1_1/DatetimeOffsets_test', _i15.main);
  group('awsJson1_1/EmptyOperation_test', _i16.main);
  group('awsJson1_1/EndpointOperation_test', _i17.main);
  group('awsJson1_1/EndpointWithHostLabelOperation_test', _i18.main);
  group('awsJson1_1/FractionalSeconds_test', _i19.main);
  group('awsJson1_1/HostWithPathOperation_test', _i20.main);
  group('awsJson1_1/JsonEnums_test', _i21.main);
  group('awsJson1_1/JsonIntEnums_test', _i22.main);
  group('awsJson1_1/JsonUnions_test', _i23.main);
  group('awsJson1_1/KitchenSinkOperation_test', _i24.main);
  group('awsJson1_1/NullOperation_test', _i25.main);
  group('awsJson1_1/OperationWithOptionalInputOutput_test', _i26.main);
  group('awsJson1_1/PutAndGetInlineDocuments_test', _i27.main);
  group('awsJson1_1/PutWithContentEncoding_test', _i28.main);
  group('awsJson1_1/SimpleScalarProperties_test', _i29.main);
  group('awsQuery/DatetimeOffsets_test', _i30.main);
  group('awsQuery/EmptyInputAndEmptyOutput_test', _i31.main);
  group('awsQuery/EndpointOperation_test', _i32.main);
  group('awsQuery/EndpointWithHostLabelOperation_test', _i33.main);
  group('awsQuery/FlattenedXmlMapWithXmlName_test', _i34.main);
  group('awsQuery/FlattenedXmlMapWithXmlNamespace_test', _i35.main);
  group('awsQuery/FlattenedXmlMap_test', _i36.main);
  group('awsQuery/FractionalSeconds_test', _i37.main);
  group('awsQuery/GreetingWithErrors_test', _i38.main);
  group('awsQuery/HostWithPathOperation_test', _i39.main);
  group('awsQuery/IgnoresWrappingXmlName_test', _i40.main);
  group('awsQuery/NestedStructures_test', _i41.main);
  group('awsQuery/NoInputAndNoOutput_test', _i42.main);
  group('awsQuery/NoInputAndOutput_test', _i43.main);
  group('awsQuery/PutWithContentEncoding_test', _i44.main);
  group('awsQuery/QueryIdempotencyTokenAutoFill_test', _i45.main);
  group('awsQuery/QueryLists_test', _i46.main);
  group('awsQuery/QueryMaps_test', _i47.main);
  group('awsQuery/QueryTimestamps_test', _i48.main);
  group('awsQuery/RecursiveXmlShapes_test', _i49.main);
  group('awsQuery/SimpleInputParams_test', _i50.main);
  group('awsQuery/SimpleScalarXmlProperties_test', _i51.main);
  group('awsQuery/XmlBlobs_test', _i52.main);
  group('awsQuery/XmlEmptyBlobs_test', _i53.main);
  group('awsQuery/XmlEmptyLists_test', _i54.main);
  group('awsQuery/XmlEmptyMaps_test', _i55.main);
  group('awsQuery/XmlEnums_test', _i56.main);
  group('awsQuery/XmlIntEnums_test', _i57.main);
  group('awsQuery/XmlLists_test', _i58.main);
  group('awsQuery/XmlMapsXmlName_test', _i59.main);
  group('awsQuery/XmlMaps_test', _i60.main);
  group('awsQuery/XmlNamespaces_test', _i61.main);
  group('awsQuery/XmlTimestamps_test', _i62.main);
  group('restJson1/ConstantAndVariableQueryString_test', _i63.main);
  group('restJson1/ConstantQueryString_test', _i64.main);
  group('restJson1/ContentTypeParameters_test', _i65.main);
  group('restJson1/DatetimeOffsets_test', _i66.main);
  group('restJson1/DocumentTypeAsMapValue_test', _i67.main);
  group('restJson1/DocumentTypeAsPayload_test', _i68.main);
  group('restJson1/DocumentType_test', _i69.main);
  group('restJson1/EmptyInputAndEmptyOutput_test', _i70.main);
  group('restJson1/EndpointOperation_test', _i71.main);
  group('restJson1/EndpointWithHostLabelOperation_test', _i72.main);
  group('restJson1/FractionalSeconds_test', _i73.main);
  group('restJson1/GreetingWithErrors_test', _i74.main);
  group('restJson1/HostWithPathOperation_test', _i75.main);
  group('restJson1/HttpChecksumRequired_test', _i76.main);
  group('restJson1/HttpEmptyPrefixHeaders_test', _i77.main);
  group('restJson1/HttpEnumPayload_test', _i78.main);
  group('restJson1/HttpPayloadTraitsWithMediaType_test', _i79.main);
  group('restJson1/HttpPayloadTraits_test', _i80.main);
  group('restJson1/HttpPayloadWithStructure_test', _i81.main);
  group('restJson1/HttpPayloadWithUnion_test', _i82.main);
  group('restJson1/HttpPrefixHeadersInResponse_test', _i83.main);
  group('restJson1/HttpPrefixHeaders_test', _i84.main);
  group('restJson1/HttpQueryParamsOnlyOperation_test', _i85.main);
  group('restJson1/HttpRequestWithFloatLabels_test', _i86.main);
  group('restJson1/HttpRequestWithGreedyLabelInPath_test', _i87.main);
  group('restJson1/HttpRequestWithLabelsAndTimestampFormat_test', _i88.main);
  group('restJson1/HttpRequestWithRegexLiteral_test', _i89.main);
  group('restJson1/HttpResponseCode_test', _i90.main);
  group('restJson1/HttpStringPayload_test', _i91.main);
  group('restJson1/IgnoreQueryParamsInResponse_test', _i92.main);
  group('restJson1/InputAndOutputWithHeaders_test', _i93.main);
  group('restJson1/JsonBlobs_test', _i94.main);
  group('restJson1/JsonEnums_test', _i95.main);
  group('restJson1/JsonIntEnums_test', _i96.main);
  group('restJson1/JsonLists_test', _i97.main);
  group('restJson1/JsonMaps_test', _i98.main);
  group('restJson1/JsonTimestamps_test', _i99.main);
  group('restJson1/JsonUnions_test', _i100.main);
  group('restJson1/MediaTypeHeader_test', _i101.main);
  group('restJson1/NoInputAndNoOutput_test', _i102.main);
  group('restJson1/NoInputAndOutput_test', _i103.main);
  group('restJson1/NullAndEmptyHeadersClient_test', _i104.main);
  group('restJson1/NullAndEmptyHeadersServer_test', _i105.main);
  group('restJson1/OmitsNullSerializesEmptyString_test', _i106.main);
  group('restJson1/OmitsSerializingEmptyLists_test', _i107.main);
  group('restJson1/OperationWithDefaults_test', _i108.main);
  group('restJson1/PostPlayerAction_test', _i109.main);
  group('restJson1/PostUnionWithJsonName_test', _i110.main);
  group('restJson1/PutWithContentEncoding_test', _i111.main);
  group('restJson1/QueryIdempotencyTokenAutoFill_test', _i112.main);
  group('restJson1/QueryParamsAsStringListMap_test', _i113.main);
  group('restJson1/QueryPrecedence_test', _i114.main);
  group('restJson1/RecursiveShapes_test', _i115.main);
  group('restJson1/ResponseCodeHttpFallback_test', _i116.main);
  group('restJson1/ResponseCodeRequired_test', _i117.main);
  group('restJson1/SimpleScalarProperties_test', _i118.main);
  group('restJson1/SparseJsonLists_test', _i119.main);
  group('restJson1/StreamingTraitsRequireLength_test', _i120.main);
  group('restJson1/StreamingTraitsWithMediaType_test', _i121.main);
  group('restJson1/StreamingTraits_test', _i122.main);
  group('restJson1/TestBodyStructure_test', _i123.main);
  group('restJson1/TestGetNoInputNoPayload_test', _i124.main);
  group('restJson1/TestGetNoPayload_test', _i125.main);
  group('restJson1/TestPayloadBlob_test', _i126.main);
  group('restJson1/TestPayloadStructure_test', _i127.main);
  group('restJson1/TestPostNoInputNoPayload_test', _i128.main);
  group('restJson1/TestPostNoPayload_test', _i129.main);
  group('restJson1/TimestampFormatHeaders_test', _i130.main);
  group('restJson1/UnitInputAndOutput_test', _i131.main);
  group('restXml/BodyWithXmlName_test', _i132.main);
  group('restXml/ConstantAndVariableQueryString_test', _i133.main);
  group('restXml/ConstantQueryString_test', _i134.main);
  group('restXml/ContentTypeParameters_test', _i135.main);
  group('restXml/DatetimeOffsets_test', _i136.main);
  group('restXml/EmptyInputAndEmptyOutput_test', _i137.main);
  group('restXml/EndpointOperation_test', _i138.main);
  group('restXml/EndpointWithHostLabelHeaderOperation_test', _i139.main);
  group('restXml/EndpointWithHostLabelOperation_test', _i140.main);
  group('restXml/FlattenedXmlMapWithXmlName_test', _i141.main);
  group('restXml/FlattenedXmlMapWithXmlNamespace_test', _i142.main);
  group('restXml/FlattenedXmlMap_test', _i143.main);
  group('restXml/FractionalSeconds_test', _i144.main);
  group('restXml/GreetingWithErrors_test', _i145.main);
  group('restXml/HttpEmptyPrefixHeaders_test', _i146.main);
  group('restXml/HttpEnumPayload_test', _i147.main);
  group('restXml/HttpPayloadTraitsWithMediaType_test', _i148.main);
  group('restXml/HttpPayloadTraits_test', _i149.main);
  group('restXml/HttpPayloadWithMemberXmlName_test', _i150.main);
  group('restXml/HttpPayloadWithStructure_test', _i151.main);
  group('restXml/HttpPayloadWithUnion_test', _i152.main);
  group('restXml/HttpPayloadWithXmlName_test', _i153.main);
  group('restXml/HttpPayloadWithXmlNamespaceAndPrefix_test', _i154.main);
  group('restXml/HttpPayloadWithXmlNamespace_test', _i155.main);
  group('restXml/HttpPrefixHeaders_test', _i156.main);
  group('restXml/HttpRequestWithFloatLabels_test', _i157.main);
  group('restXml/HttpRequestWithGreedyLabelInPath_test', _i158.main);
  group('restXml/HttpRequestWithLabelsAndTimestampFormat_test', _i159.main);
  group('restXml/HttpResponseCode_test', _i160.main);
  group('restXml/HttpStringPayload_test', _i161.main);
  group('restXml/IgnoreQueryParamsInResponse_test', _i162.main);
  group('restXml/InputAndOutputWithHeaders_test', _i163.main);
  group('restXml/NestedXmlMapWithXmlName_test', _i164.main);
  group('restXml/NestedXmlMaps_test', _i165.main);
  group('restXml/NoInputAndNoOutput_test', _i166.main);
  group('restXml/NoInputAndOutput_test', _i167.main);
  group('restXml/NullAndEmptyHeadersClient_test', _i168.main);
  group('restXml/NullAndEmptyHeadersServer_test', _i169.main);
  group('restXml/OmitsNullSerializesEmptyString_test', _i170.main);
  group('restXml/PutWithContentEncoding_test', _i171.main);
  group('restXml/QueryIdempotencyTokenAutoFill_test', _i172.main);
  group('restXml/QueryParamsAsStringListMap_test', _i173.main);
  group('restXml/QueryPrecedence_test', _i174.main);
  group('restXml/RecursiveShapes_test', _i175.main);
  group('restXml/SimpleScalarProperties_test', _i176.main);
  group('restXml/TimestampFormatHeaders_test', _i177.main);
  group('restXml/XmlAttributesInMiddle_test', _i178.main);
  group('restXml/XmlAttributesOnPayload_test', _i179.main);
  group('restXml/XmlAttributes_test', _i180.main);
  group('restXml/XmlBlobs_test', _i181.main);
  group('restXml/XmlEmptyBlobs_test', _i182.main);
  group('restXml/XmlEmptyLists_test', _i183.main);
  group('restXml/XmlEmptyMaps_test', _i184.main);
  group('restXml/XmlEmptyStrings_test', _i185.main);
  group('restXml/XmlEnums_test', _i186.main);
  group('restXml/XmlIntEnums_test', _i187.main);
  group('restXml/XmlLists_test', _i188.main);
  group('restXml/XmlMapWithXmlNamespace_test', _i189.main);
  group('restXml/XmlMapsXmlName_test', _i190.main);
  group('restXml/XmlMaps_test', _i191.main);
  group('restXml/XmlNamespaces_test', _i192.main);
  group('restXml/XmlTimestamps_test', _i193.main);
  group('restXml/XmlUnions_test', _i194.main);
}
