import '../utils/case.dart';

/// Compiles a Smithy `endpointRuleSet` into a Dart `resolveEndpoint` function.
String buildEndpointResolverFile(Map<String, Object?> ruleSet) =>
    _Compiler(ruleSet).build();

const _resolverImport =
    '../../shared/src/protocol/endpoints/endpoint_resolver.dart';
const _functionsImport =
    '../../shared/src/protocol/endpoints/endpoint_functions.dart';

const _boolFns = {
  'booleanEquals',
  'stringEquals',
  'isSet',
  'not',
  'isValidHostLabel',
  'aws.isVirtualHostableS3Bucket',
};

// Functions whose result is never null in our runtime (unlike Smithy's optional
// model), so the rules' "is set" check on them is always true.
const _nonNullFns = {'aws.partition', 'uriEncode'};

class _Compiler {
  final Map<String, Object?> ruleSet;
  final StringBuffer _out = StringBuffer();

  // Rule-set var -> Dart identifier, snapshotted per rule so assigns don't leak.
  final Map<String, String> _names = {};

  // Rule-set var -> value kind (partition/arn/url), for typed getAttr access.
  final Map<String, String> _kinds = {};

  final Set<String> _used = {};

  // Dart identifiers proven non-null in the current scope, and those that are
  // String-typed — together they let us drop redundant null checks and casts.
  final Set<String> _nonNull = {};
  final Set<String> _stringIds = {};

  _Compiler(this.ruleSet);

  void _line(int indent, String text) => _out.writeln('${'  ' * indent}$text');

  String build() {
    final parameters =
        (ruleSet['parameters'] as Map?)?.cast<String, Object?>() ?? const {};

    // Fixed names so every resolver matches the shared signature; reserve them
    // so assigned locals never collide.
    _used.addAll(const ['region', 'endpoint', 'useFips', 'useDualStack']);

    final serviceParams = <String>[];
    for (final entry in parameters.entries) {
      final spec = (entry.value as Map).cast<String, Object?>();
      final fixed = switch (spec['builtIn']) {
        'AWS::Region' => 'region',
        'SDK::Endpoint' => 'endpoint',
        'AWS::UseFIPS' => 'useFips',
        'AWS::UseDualStack' => 'useDualStack',
        _ => null,
      };
      if (fixed != null) {
        _register(entry.key, fixed);
        if (fixed == 'region' || fixed == 'endpoint') _stringIds.add(fixed);
      } else {
        final name = lowerCamel(splitWords(entry.key));
        _register(entry.key, name);
        if (spec['type'] == 'string') _stringIds.add(name);
        serviceParams.add(_serviceParamDecl(name, spec));
      }
    }

    _out
      ..writeln('// AUTO-GENERATED: This file is generated by the `generator` '
          'package.')
      ..writeln('//')
      ..writeln('// The AWS endpoint resolver for this service, compiled from '
          'its')
      ..writeln('// `smithy.rules#endpointRuleSet` trait.')
      ..writeln()
      ..writeln('// ignore_for_file: unnecessary_null_comparison, '
          'unnecessary_string_interpolations')
      ..writeln()
      ..writeln("import '$_functionsImport' as fn;")
      ..writeln("import '$_resolverImport';")
      ..writeln()
      ..writeln('ResolvedEndpoint resolveEndpoint({')
      ..writeln('  String? region,')
      ..writeln('  String? endpoint,')
      ..writeln('  bool useFips = false,')
      ..writeln('  bool useDualStack = false,');
    for (final decl in serviceParams) {
      _out.writeln('  $decl,');
    }
    _out.writeln('}) {');

    final rules = (ruleSet['rules'] as List).cast<Object?>();
    _emitRules(rules, 1);

    if (!_alwaysReturns(rules)) {
      _line(1,
          "throw EndpointResolutionException('No endpoint rule matched the parameters');");
    }
    _out.writeln('}');
    return _out.toString();
  }

  // Whether the rules always return/throw, making a trailing fallback unreachable.
  bool _alwaysReturns(List<Object?> rules) {
    for (final raw in rules) {
      final rule = (raw as Map).cast<String, Object?>();
      final conditions =
          ((rule['conditions'] as List?) ?? const []).cast<Object?>();
      // Non-null-fn conditions always pass, so they don't actually guard.
      final guarded = conditions.any((c) =>
          !_nonNullFns.contains((c as Map).cast<String, Object?>()['fn']));
      if (guarded) continue;
      switch (rule['type']) {
        case 'endpoint':
        case 'error':
          return true;
        case 'tree':
          if (_alwaysReturns((rule['rules'] as List).cast<Object?>())) {
            return true;
          }
      }
    }
    return false;
  }

  void _emitRules(List<Object?> rules, int indent) {
    for (final raw in rules) {
      final rule = (raw as Map).cast<String, Object?>();
      final conditions =
          (rule['conditions'] as List?)?.cast<Object?>() ?? const [];
      final hasAssign = conditions
          .any((c) => (c as Map).cast<String, Object?>()['assign'] != null);
      final savedNames = Map<String, String>.of(_names);
      final savedKinds = Map<String, String>.of(_kinds);
      final savedNonNull = Set<String>.of(_nonNull);
      final savedStringIds = Set<String>.of(_stringIds);

      if (hasAssign) {
        // An `assign` declares a local scoped to this rule's subtree, so wrap it
        // in a block.
        _line(indent, '{');
        final r = _conditions(conditions, indent + 1, rule, emitAssigns: true);
        _nonNull.addAll(r.proven);
        _emitGuarded(rule, r.terms, indent + 1);
        _line(indent, '}');
      } else {
        final r = _conditions(conditions, indent, rule, emitAssigns: false);
        _nonNull.addAll(r.proven);
        _emitGuarded(rule, r.terms, indent);
      }

      _names
        ..clear()
        ..addAll(savedNames);
      _kinds
        ..clear()
        ..addAll(savedKinds);
      _nonNull
        ..clear()
        ..addAll(savedNonNull);
      _stringIds
        ..clear()
        ..addAll(savedStringIds);
    }
  }

  // Emits assigns and returns the guard terms plus the ids it proves non-null.
  // Always-true terms (is-set of a total fn or already-non-null ref) are dropped.
  ({List<String> terms, Set<String> proven}) _conditions(
      List<Object?> conditions, int indent, Map<String, Object?> rule,
      {required bool emitAssigns}) {
    final terms = <String>[];
    final proven = <String>{};
    for (final raw in conditions) {
      final condition = (raw as Map).cast<String, Object?>();
      final fn = condition['fn'];
      final assign = condition['assign'] as String?;

      // An unused assign of a total function is dead weight — skip it.
      if (assign != null &&
          emitAssigns &&
          _nonNullFns.contains(fn) &&
          !_refOccurs(assign, rule)) {
        continue;
      }

      String? assignedId;
      if (assign != null && emitAssigns) {
        assignedId = _declare(assign, kind: _kindForFn(fn));
        if (fn == 'substring' || fn == 'uriEncode') _stringIds.add(assignedId);
        _line(indent, 'final $assignedId = ${_fnExpr(condition)};');
      }

      if (_nonNullFns.contains(fn)) {
        if (assignedId != null) proven.add(assignedId);
        continue;
      }
      if (fn == 'isSet') {
        final refId = _isSetRefId(condition);
        if (refId != null && _nonNull.contains(refId)) continue;
        if (refId != null) proven.add(refId);
        terms.add(assignedId ?? _fnExpr(condition));
        continue;
      }
      if (_boolFns.contains(fn)) {
        terms.add(assignedId ?? _fnExpr(condition));
        continue;
      }
      if (assignedId != null) {
        terms.add('$assignedId != null');
        proven.add(assignedId);
      } else {
        terms.add('${_fnExpr(condition)} != null');
      }
    }
    return (terms: terms, proven: proven);
  }

  String? _isSetRefId(Map<String, Object?> condition) {
    final argv = condition['argv'] as List?;
    if (argv == null || argv.isEmpty) return null;
    final a = argv[0];
    return (a is Map && a.length == 1 && a.containsKey('ref'))
        ? _ref(a['ref'] as String)
        : null;
  }

  // Whether [name] is referenced in [node], as a `{ref}` or `{name}`/`{name#...}`.
  bool _refOccurs(String name, Object? node) {
    if (node is Map) {
      if (node.length == 1 && node['ref'] == name) return true;
      return node.values.any((v) => _refOccurs(name, v));
    }
    if (node is List) return node.any((v) => _refOccurs(name, v));
    if (node is String) return RegExp('\\{$name[#}]').hasMatch(node);
    return false;
  }

  void _emitGuarded(Map<String, Object?> rule, List<String> terms, int indent) {
    if (terms.isEmpty) {
      _emitBody(rule, indent);
      return;
    }
    final guard = terms.length == 1
        ? terms.single
        : terms.map((t) => '($t)').join(' && ');
    _line(indent, 'if ($guard) {');
    _emitBody(rule, indent + 1);
    _line(indent, '}');
  }

  void _emitBody(Map<String, Object?> rule, int indent) {
    switch (rule['type']) {
      case 'endpoint':
        _emitEndpoint(
            (rule['endpoint'] as Map).cast<String, Object?>(), indent);
      case 'error':
        _line(indent,
            'throw EndpointResolutionException(${_stringValue(rule['error'])});');
      case 'tree':
        _emitRules((rule['rules'] as List).cast<Object?>(), indent);
      default:
        throw StateError('Unknown endpoint rule type: ${rule['type']}');
    }
  }

  void _emitEndpoint(Map<String, Object?> endpoint, int indent) {
    final url = _stringValue(endpoint['url']);
    final args = <String>['url: $url'];

    final properties =
        (endpoint['properties'] as Map?)?.cast<String, Object?>() ?? const {};
    final rawSchemes = properties['authSchemes'];
    if (rawSchemes is List && rawSchemes.isNotEmpty) {
      final schemes = rawSchemes.map((raw) {
        final scheme = (raw as Map).cast<String, Object?>();
        final parts = <String>['name: ${_stringValue(scheme['name'])}'];
        if (scheme.containsKey('signingName')) {
          parts.add('signingName: ${_stringValue(scheme['signingName'])}');
        }
        if (scheme.containsKey('signingRegion')) {
          parts.add('signingRegion: ${_stringValue(scheme['signingRegion'])}');
        }
        if (scheme['signingRegionSet'] is List) {
          final set =
              (scheme['signingRegionSet'] as List).map(_stringValue).join(', ');
          parts.add('signingRegionSet: [$set]');
        }
        if (scheme.containsKey('disableDoubleEncoding')) {
          parts.add(
              'disableDoubleEncoding: ${_literal(scheme['disableDoubleEncoding'])}');
        }
        return 'EndpointAuthScheme(${parts.join(', ')})';
      }).join(', ');
      args.add('authSchemes: [$schemes]');
    }

    final rawHeaders = endpoint['headers'];
    if (rawHeaders is Map && rawHeaders.isNotEmpty) {
      final headers = rawHeaders.entries.map((e) {
        final values = (e.value as List).map(_stringValue).join(', ');
        return '${_literal('${e.key}')}: [$values]';
      }).join(', ');
      args.add('headers: {$headers}');
    }

    _line(indent, 'return ResolvedEndpoint(${args.join(', ')});');
  }

  String _fnExpr(Map<String, Object?> node) {
    if (node['fn'] == 'getAttr') {
      final raw = node['argv'] as List;
      return _compileGetAttr(raw[0], raw[1] as String);
    }
    final argv =
        (node['argv'] as List?)?.map(_value).toList() ?? const <String>[];
    switch (node['fn']) {
      case 'isSet':
        return '${argv[0]} != null';
      case 'not':
        return '!(${argv[0]})';
      case 'booleanEquals':
      case 'stringEquals':
        return '${argv[0]} == ${argv[1]}';
      case 'aws.partition':
        return 'fn.awsPartition(${argv[0]})';
      case 'aws.parseArn':
        return 'fn.parseArn(${argv[0]})';
      case 'aws.isVirtualHostableS3Bucket':
        return 'fn.isVirtualHostableS3Bucket(${argv[0]}, ${argv[1]})';
      case 'substring':
        return 'fn.substring(${argv[0]}, ${argv[1]}, ${argv[2]}, ${argv[3]})';
      case 'isValidHostLabel':
        return 'fn.isValidHostLabel(${argv[0]}, ${argv[1]})';
      case 'parseURL':
        return 'fn.parseUrl(${argv[0]})';
      case 'uriEncode':
        return 'fn.uriEncode(${argv[0]})';
      default:
        throw StateError('Unsupported endpoint function: ${node['fn']}');
    }
  }

  String _compileGetAttr(Object? target, String path) {
    if (target is Map && target.length == 1 && target.containsKey('ref')) {
      final name = target['ref'] as String;
      final fields = _fieldsForKind(_kinds[name]);
      if (fields != null) {
        return _typedAccess(_ref(name), fields, path);
      }
    }
    return 'fn.getAttr(${_value(target)}, ${_literal(path)})';
  }

  String _typedAccess(String target, Map<String, String> fields, String path) {
    final segments = _pathSegments(path);
    final first = segments.first as String;
    var expr = '$target.${fields[first] ?? first}';
    for (final segment in segments.skip(1)) {
      expr = segment is int
          ? 'fn.elementOrNull($expr, $segment)'
          : '$expr.$segment';
    }
    return expr;
  }

  List<Object> _pathSegments(String path) {
    final segments = <Object>[];
    for (final part in path.split('.')) {
      final bracket = part.indexOf('[');
      if (bracket < 0) {
        if (part.isNotEmpty) segments.add(part);
      } else {
        final name = part.substring(0, bracket);
        if (name.isNotEmpty) segments.add(name);
        segments.add(int.parse(part.substring(bracket + 1, part.indexOf(']'))));
      }
    }
    return segments;
  }

  String _kindForFn(Object? fn) => switch (fn) {
        'aws.partition' => 'partition',
        'aws.parseArn' => 'arn',
        'parseURL' => 'url',
        _ => 'dynamic',
      };

  Map<String, String>? _fieldsForKind(String? kind) => switch (kind) {
        'partition' => _partitionFields,
        'arn' => _arnFields,
        'url' => _urlFields,
        _ => null,
      };

  String _value(Object? node) {
    if (node is Map) {
      final map = node.cast<String, Object?>();
      if (map.length == 1 && map.containsKey('ref')) {
        return _ref(map['ref'] as String);
      }
      return _fnExpr(map);
    }
    if (node is String) {
      return node.contains('{') ? _template(node) : _literal(node);
    }
    return _literal(node);
  }

  // Like _value but always String-typed. Refs are cast since params are Object?,
  // except when already known to be a non-null String.
  String _stringValue(Object? node) {
    if (node is String) {
      return node.contains('{') ? _template(node) : _literal(node);
    }
    if (node is Map && node.length == 1 && node.containsKey('ref')) {
      final id = _ref(node['ref'] as String);
      if (_nonNull.contains(id) && _stringIds.contains(id)) return id;
      return '$id as String';
    }
    return '${_value(node)} as String';
  }

  String _template(String template) {
    // A whole-string single interpolation is just the expression, when it's
    // already a non-null String — no need to wrap it in a literal.
    final single = RegExp(r'^\{([^{}]+)\}$').firstMatch(template);
    if (single != null) {
      final expr = _templateExpr(single.group(1)!);
      if (RegExp(r'^[\w$]+(\.[\w$]+)+$').hasMatch(expr) ||
          (RegExp(r'^[\w$]+$').hasMatch(expr) &&
              _nonNull.contains(expr) &&
              _stringIds.contains(expr))) {
        return expr;
      }
    }

    final buffer = StringBuffer("'");
    var i = 0;
    while (i < template.length) {
      final char = template[i];
      if (char == '{') {
        if (i + 1 < template.length && template[i + 1] == '{') {
          buffer.write('{');
          i += 2;
          continue;
        }
        final end = template.indexOf('}', i);
        final expression = template.substring(i + 1, end);
        final expr = _templateExpr(expression);
        final nextChar = end + 1 < template.length ? template[end + 1] : '';
        // Drop the braces for a bare identifier, unless the next literal char
        // would extend it (`$fooBar`).
        if (RegExp(r'^[a-zA-Z_][a-zA-Z0-9_$]*$').hasMatch(expr) &&
            !RegExp(r'[a-zA-Z0-9_]').hasMatch(nextChar)) {
          buffer.write('\$$expr');
        } else {
          buffer.write('\${$expr}');
        }
        i = end + 1;
      } else if (char == '}' &&
          i + 1 < template.length &&
          template[i + 1] == '}') {
        buffer.write('}');
        i += 2;
      } else {
        buffer.write(_escapeChar(char));
        i++;
      }
    }
    buffer.write("'");
    return buffer.toString();
  }

  String _templateExpr(String expression) {
    final hash = expression.indexOf('#');
    if (hash < 0) return _ref(expression);
    final name = expression.substring(0, hash);
    final path = expression.substring(hash + 1);
    final fields = _fieldsForKind(_kinds[name]);
    return fields != null
        ? _typedAccess(_ref(name), fields, path)
        : 'fn.getAttr(${_ref(name)}, ${_literal(path)})';
  }

  void _register(String name, String dartName, {String kind = 'dynamic'}) {
    _names[name] = dartName;
    _used.add(dartName);
    _kinds[name] = kind;
  }

  // Params without a default stay nullable so the rules can tell "unset" (isSet
  // false) from an explicit false/empty value.
  String _serviceParamDecl(String dartName, Map<String, Object?> spec) {
    final hasDefault = spec.containsKey('default');
    return switch (spec['type']) {
      'boolean' => hasDefault
          ? 'bool $dartName = ${_literal(spec['default'])}'
          : 'bool? $dartName',
      'string' => hasDefault
          ? 'String $dartName = ${_literal(spec['default'])}'
          : 'String? $dartName',
      'stringArray' => 'List<String>? $dartName',
      _ => 'Object? $dartName',
    };
  }

  String _ref(String name) => _names[name] ?? lowerCamel(splitWords(name));

  String _declare(String name, {String kind = 'dynamic'}) {
    var candidate = lowerCamel(splitWords(name));
    if (candidate.isEmpty || _dartKeywords.contains(candidate)) {
      candidate = '\$$candidate';
    }
    var unique = candidate;
    var n = 2;
    while (_used.contains(unique)) {
      unique = '$candidate$n';
      n++;
    }
    _used.add(unique);
    _names[name] = unique;
    _kinds[name] = kind;
    return unique;
  }

  String _literal(Object? value) {
    if (value == null) return 'null';
    if (value is bool || value is num) return '$value';
    if (value is String) {
      return "'${value.split('').map(_escapeChar).join()}'";
    }
    throw ArgumentError('Cannot render literal of type ${value.runtimeType}');
  }

  String _escapeChar(String char) {
    switch (char) {
      case r'\':
        return r'\\';
      case "'":
        return r"\'";
      case r'$':
        return r'\$';
      case '\n':
        return r'\n';
      case '\r':
        return r'\r';
      case '\t':
        return r'\t';
      default:
        return char;
    }
  }
}

const _partitionFields = {
  'name': 'name',
  'dnsSuffix': 'dnsSuffix',
  'dualStackDnsSuffix': 'dualStackDnsSuffix',
  'supportsFIPS': 'supportsFips',
  'supportsDualStack': 'supportsDualStack',
  'implicitGlobalRegion': 'implicitGlobalRegion',
};

const _arnFields = {
  'partition': 'partition',
  'service': 'service',
  'region': 'region',
  'accountId': 'accountId',
  'resourceId': 'resourceId',
};

const _urlFields = {
  'scheme': 'scheme',
  'authority': 'authority',
  'path': 'path',
  'normalizedPath': 'normalizedPath',
  'isIp': 'isIp',
};

const _dartKeywords = {
  'assert',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'default',
  'do',
  'else',
  'enum',
  'extends',
  'false',
  'final',
  'finally',
  'for',
  'if',
  'in',
  'is',
  'new',
  'null',
  'rethrow',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'var',
  'void',
  'while',
  'with',
  'dynamic',
};
