import '../utils/case.dart';

/// Generates a service's endpoint-resolution conformance test from its
/// `endpointTests` cases.
String buildEndpointTestsFile({
  required String directoryName,
  required String fileBasename,
  required List<Object?> testCases,
}) {
  final tests = StringBuffer();
  for (var i = 0; i < testCases.length; i++) {
    final testCase = (testCases[i] as Map).cast<String, Object?>();
    final expect = (testCase['expect'] as Map?)?.cast<String, Object?>();
    if (expect == null) continue;
    // Cases that only exercise operation context inputs (no built-in params)
    // are covered by the protocol suite; resolve from `params` here.
    final params =
        (testCase['params'] as Map?)?.cast<String, Object?>() ?? const {};
    final doc = '${testCase['documentation'] ?? 'case $i'} [$i]';

    final args = _argsLiteral(params);
    tests.writeln('  test(${_stringLit(doc)}, () {');
    if (expect.containsKey('error')) {
      tests.writeln('    expect(');
      tests.writeln('      () => resolveEndpoint($args),');
      tests.writeln('      throwsA(isA<EndpointResolutionException>()');
      tests.writeln(
          "          .having((e) => e.message, 'message', ${_stringLit('${expect['error']}')})),");
      tests.writeln('    );');
    } else {
      final endpoint = (expect['endpoint'] as Map).cast<String, Object?>();
      tests.writeln('    final resolved = resolveEndpoint($args);');
      tests.writeln(
          '    expect(resolved.url, ${_stringLit('${endpoint['url']}')});');

      final schemes =
          ((endpoint['properties'] as Map?)?['authSchemes'] as List?) ??
              const [];
      tests.writeln(
          '    expect(resolved.authSchemes.length, ${schemes.length});');
      for (var s = 0; s < schemes.length; s++) {
        final scheme = (schemes[s] as Map).cast<String, Object?>();
        tests.writeln(
            "    expect(resolved.authSchemes[$s].name, ${_stringLit('${scheme['name']}')});");
        _expectNullableString(tests, 'resolved.authSchemes[$s].signingName',
            scheme['signingName']);
        _expectNullableString(tests, 'resolved.authSchemes[$s].signingRegion',
            scheme['signingRegion']);
        final regionSet = scheme['signingRegionSet'];
        if (regionSet is List) {
          tests.writeln(
              '    expect(resolved.authSchemes[$s].signingRegionSet, ${dartLiteral(regionSet)});');
        }
      }

      final headers =
          (endpoint['headers'] as Map?)?.cast<String, Object?>() ?? const {};
      tests.writeln(
          '    expect(resolved.headers.keys.toSet(), ${dartLiteral(headers.keys.toList())}.toSet());');
      headers.forEach((key, value) {
        tests.writeln(
            '    expect(resolved.headers[${_stringLit(key)}], ${dartLiteral(value)});');
      });
    }
    tests.writeln('  });');
  }

  return '''
// AUTO-GENERATED: This file is generated by the `generator` package.
//
// Endpoint resolution conformance tests, derived from the service's
// `smithy.rules#endpointTests` trait.

// ignore_for_file: prefer_single_quotes, prefer_collection_literals, unnecessary_lambdas, unused_import

import 'package:aws_client/src/generated/$directoryName/$fileBasename.endpoints.dart';
import 'package:aws_client/src/shared/src/protocol/endpoints/endpoint_resolver.dart';
import 'package:test/test.dart';

void main() {
$tests}
''';
}

String _argsLiteral(Map<String, Object?> params) => params.entries
    .map((e) => '${_dartParamName(e.key)}: ${dartLiteral(e.value)}')
    .join(', ');

String _dartParamName(String name) => switch (name) {
      'Region' => 'region',
      'Endpoint' => 'endpoint',
      'UseFIPS' => 'useFips',
      'UseDualStack' => 'useDualStack',
      _ => lowerCamel(splitWords(name)),
    };

String dartLiteral(Object? value) {
  if (value == null) return 'null';
  if (value is bool || value is num) return '$value';
  if (value is String) return _stringLit(value);
  if (value is List) return '[${value.map(dartLiteral).join(', ')}]';
  if (value is Map) {
    final entries = value.entries
        .map((e) => '${_stringLit('${e.key}')}: ${dartLiteral(e.value)}');
    return '{${entries.join(', ')}}';
  }
  throw ArgumentError('Cannot render value of type ${value.runtimeType}');
}

void _expectNullableString(StringBuffer out, String actual, Object? expected) {
  if (expected == null) {
    out.writeln('    expect($actual, isNull);');
  } else {
    out.writeln('    expect($actual, ${_stringLit('$expected')});');
  }
}

String _stringLit(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r')
      .replaceAll('\t', r'\t');
  return "'$escaped'";
}
