import 'dart:convert';

Map<String, String> parseSkipList(String json) {
  if (json.trim().isEmpty) return {};
  final decoded = jsonDecode(json) as Map<String, dynamic>;
  return decoded.map((k, v) => MapEntry(k, v as String));
}

List<String> staleSkipKeys(
        Map<String, String> skipList, Set<String> emittedIds) =>
    skipList.keys.where((k) => !emittedIds.contains(k)).toList();

class ProtocolReadiness {
  final String protocol;
  final int corpusVectors;
  final int vectors;
  final int skipped;
  final int excludedOps;
  final int outOfScope;
  final bool buildFailed;
  ProtocolReadiness({
    required this.protocol,
    required this.corpusVectors,
    required this.vectors,
    required this.skipped,
    required this.excludedOps,
    this.outOfScope = 0,
    this.buildFailed = false,
  });
  int get passing => vectors - skipped;
  int get applicable => corpusVectors - outOfScope;
}

String renderReadiness(List<ProtocolReadiness> rows) {
  final buf = StringBuffer()
    ..writeln('# Smithy Suite 2 — readiness')
    ..writeln()
    ..writeln('Generated by the build. Honest pass/skip/exclude counts for the '
        'official Smithy protocol conformance vectors. "Corpus" is the total '
        'vectors for the protocol; "Server" vectors (`appliesTo: "server"`) are '
        'out of scope for a client library and filtered out, so true coverage is '
        '"Passing" out of "Applicable" (= Corpus − Server).')
    ..writeln()
    ..writeln('| Protocol | Corpus | Server | Applicable | Vectors | Passing | '
        'Skipped | Excluded ops |')
    ..writeln('|---|---|---|---|---|---|---|---|');
  var c = 0, oos = 0, v = 0, p = 0, s = 0, e = 0;
  for (final r in rows) {
    final excludedCell = r.buildFailed
        ? '${r.excludedOps} (whole client failed to build)'
        : '${r.excludedOps}';
    buf.writeln(
        '| ${r.protocol} | ${r.corpusVectors} | ${r.outOfScope} | ${r.applicable} | ${r.vectors} | ${r.passing} | ${r.skipped} | $excludedCell |');
    c += r.corpusVectors;
    oos += r.outOfScope;
    v += r.vectors;
    p += r.passing;
    s += r.skipped;
    e += r.excludedOps;
  }
  buf.writeln('| **total** | **$c** | **$oos** | **${c - oos}** | **$v** | '
      '**$p** | **$s** | **$e** |');
  return '$buf';
}
