// AUTO-GENERATED: This file is generated by the `generator` package.
//
// Endpoint resolution conformance tests, derived from the service's
// `smithy.rules#endpointTests` trait.

// ignore_for_file: prefer_single_quotes, prefer_collection_literals, unnecessary_lambdas, unused_import

import 'package:aws_client/src/generated/signer_data/v2017_08_25.endpoints.dart';
import 'package:aws_client/src/shared/src/protocol/endpoints/endpoint_resolver.dart';
import 'package:test/test.dart';

void main() {
  test('Standard region endpoint [0]', () {
    final resolved = resolveEndpoint(region: 'us-east-1');
    expect(resolved.url, 'https://data-signer.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('European Sovereign Cloud region endpoint [1]', () {
    final resolved = resolveEndpoint(region: 'eusc-de-east-1');
    expect(resolved.url, 'https://data-signer.eusc-de-east-1.amazonaws.eu');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Custom endpoint override [2]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        endpoint: 'https://vpce-123.data-signer.us-east-1.vpce.amazonaws.com');
    expect(resolved.url,
        'https://vpce-123.data-signer.us-east-1.vpce.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('FIPS endpoint [3]', () {
    final resolved = resolveEndpoint(region: 'us-east-1', useFips: true);
    expect(resolved.url, 'https://data-signer-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Dual-stack endpoint [4]', () {
    final resolved = resolveEndpoint(region: 'us-east-1', useDualStack: true);
    expect(resolved.url, 'https://data-signer.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
}
