// AUTO-GENERATED: This file is generated by the `generator` package.
//
// Endpoint resolution conformance tests, derived from the service's
// `smithy.rules#endpointTests` trait.

// ignore_for_file: prefer_single_quotes, prefer_collection_literals, unnecessary_lambdas, unused_import

import 'package:aws_client/src/generated/braket/v2019_09_01.endpoints.dart';
import 'package:aws_client/src/shared/src/protocol/endpoints/endpoint_resolver.dart';
import 'package:test/test.dart';

void main() {
  test('For region eu-west-2 with FIPS disabled and DualStack disabled [0]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://braket.eu-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack disabled [1]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://braket.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-1 with FIPS disabled and DualStack disabled [2]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://braket.us-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-2 with FIPS disabled and DualStack disabled [3]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://braket.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS enabled and DualStack enabled [4]', () {
    final resolved =
        resolveEndpoint(region: 'us-east-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://braket-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS enabled and DualStack disabled [5]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://braket-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack enabled [6]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://braket.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS enabled and DualStack enabled [7]', () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: true, useDualStack: true);
    expect(resolved.url,
        'https://braket-fips.cn-north-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS enabled and DualStack disabled [8]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://braket-fips.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS disabled and DualStack enabled [9]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: false, useDualStack: true);
    expect(
        resolved.url, 'https://braket.cn-north-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS disabled and DualStack disabled [10]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://braket.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS enabled and DualStack enabled [11]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://braket-fips.us-gov-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS enabled and DualStack disabled [12]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://braket-fips.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS disabled and DualStack enabled [13]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://braket.us-gov-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-gov-east-1 with FIPS disabled and DualStack disabled [14]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://braket.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-iso-east-1 with FIPS enabled and DualStack disabled [15]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://braket-fips.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-iso-east-1 with FIPS disabled and DualStack disabled [16]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://braket.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isob-east-1 with FIPS enabled and DualStack disabled [17]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://braket-fips.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isob-east-1 with FIPS disabled and DualStack disabled [18]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://braket.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For custom endpoint with region set and fips disabled and dualstack disabled [19]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For custom endpoint with region not set and fips disabled and dualstack disabled [20]',
      () {
    final resolved = resolveEndpoint(
        useFips: false, useDualStack: false, endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For custom endpoint with fips enabled and dualstack disabled [21]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: true,
          useDualStack: false,
          endpoint: 'https://example.com'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: FIPS and custom endpoint are not supported')),
    );
  });
  test('For custom endpoint with fips disabled and dualstack enabled [22]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: true,
          endpoint: 'https://example.com'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: Dualstack and custom endpoint are not supported')),
    );
  });
  test('Missing region [23]', () {
    expect(
      () => resolveEndpoint(),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid Configuration: Missing Region')),
    );
  });
}
