name: aws_client
description: High-level APIs for Amazon Web Services (AWS)
version: 0.4.0

homepage: https://github.com/agilord/aws_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  http: ^0.13.1
  meta: ^1.3.0
  xml:  '>=6.0.0 <7.0.0'
  intl: '>=0.17.0 <0.19.0'
  uuid: ^3.0.3
  collection: ^1.15.0

dev_dependencies:
  lints:
  test:
