name: aws_client
description: High-level APIs for Amazon Web Services (AWS)
version: 0.3.0-dev
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/aws_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  http: ^0.13.1
  meta: ^1.3.0
  xml: ^5.0.2
  intl: ^0.17.0
  uuid: ^3.0.3
  collection: ^1.15.0

dev_dependencies:
  pedantic:
  test: