// AUTO-GENERATED: This file is generated by the `generator` package.
//
// Endpoint resolution conformance tests, derived from the service's
// `smithy.rules#endpointTests` trait.

// ignore_for_file: prefer_single_quotes, prefer_collection_literals, unnecessary_lambdas, unused_import

import 'package:aws_client/src/generated/kinesis/v2013_12_02.endpoints.dart';
import 'package:aws_client/src/shared/src/protocol/endpoints/endpoint_resolver.dart';
import 'package:test/test.dart';

void main() {
  test('For region af-south-1 with FIPS disabled and DualStack disabled [0]',
      () {
    final resolved = resolveEndpoint(
        region: 'af-south-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.af-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ap-east-1 with FIPS disabled and DualStack disabled [1]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.ap-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-northeast-1 with FIPS disabled and DualStack disabled [2]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-northeast-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.ap-northeast-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-northeast-2 with FIPS disabled and DualStack disabled [3]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-northeast-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.ap-northeast-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-northeast-3 with FIPS disabled and DualStack disabled [4]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-northeast-3', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.ap-northeast-3.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ap-south-1 with FIPS disabled and DualStack disabled [5]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-south-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.ap-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-southeast-1 with FIPS disabled and DualStack disabled [6]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-southeast-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.ap-southeast-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-southeast-2 with FIPS disabled and DualStack disabled [7]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-southeast-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.ap-southeast-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-southeast-3 with FIPS disabled and DualStack disabled [8]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-southeast-3', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.ap-southeast-3.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ca-central-1 with FIPS disabled and DualStack disabled [9]',
      () {
    final resolved = resolveEndpoint(
        region: 'ca-central-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.ca-central-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-central-1 with FIPS disabled and DualStack disabled [10]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-central-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.eu-central-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-north-1 with FIPS disabled and DualStack disabled [11]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-north-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.eu-north-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-south-1 with FIPS disabled and DualStack disabled [12]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-south-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.eu-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-1 with FIPS disabled and DualStack disabled [13]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.eu-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-2 with FIPS disabled and DualStack disabled [14]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.eu-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-3 with FIPS disabled and DualStack disabled [15]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-3', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.eu-west-3.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region me-south-1 with FIPS disabled and DualStack disabled [16]',
      () {
    final resolved = resolveEndpoint(
        region: 'me-south-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.me-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region sa-east-1 with FIPS disabled and DualStack disabled [17]',
      () {
    final resolved = resolveEndpoint(
        region: 'sa-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.sa-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack disabled [18]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS enabled and DualStack disabled [19]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-2 with FIPS disabled and DualStack disabled [20]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-2 with FIPS enabled and DualStack disabled [21]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-2', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://kinesis-fips.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-1 with FIPS disabled and DualStack disabled [22]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-1 with FIPS enabled and DualStack disabled [23]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://kinesis-fips.us-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-2 with FIPS disabled and DualStack disabled [24]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-2 with FIPS enabled and DualStack disabled [25]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-2', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://kinesis-fips.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS enabled and DualStack enabled [26]', () {
    final resolved =
        resolveEndpoint(region: 'us-east-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://kinesis-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack enabled [27]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://kinesis.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS disabled and DualStack disabled [28]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region cn-northwest-1 with FIPS disabled and DualStack disabled [29]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.cn-northwest-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS enabled and DualStack enabled [30]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: true, useDualStack: true);
    expect(resolved.url,
        'https://kinesis-fips.cn-north-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS enabled and DualStack disabled [31]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://kinesis-fips.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS disabled and DualStack enabled [32]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: false, useDualStack: true);
    expect(resolved.url,
        'https://kinesis.cn-north-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-gov-east-1 with FIPS disabled and DualStack disabled [33]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS enabled and DualStack disabled [34]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-gov-west-1 with FIPS disabled and DualStack disabled [35]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-gov-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-west-1 with FIPS enabled and DualStack disabled [36]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-gov-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS enabled and DualStack enabled [37]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://kinesis-fips.us-gov-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS disabled and DualStack enabled [38]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://kinesis.us-gov-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-iso-east-1 with FIPS disabled and DualStack disabled [39]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-iso-west-1 with FIPS disabled and DualStack disabled [40]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-iso-west-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-iso-east-1 with FIPS enabled and DualStack disabled [41]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://kinesis-fips.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isob-east-1 with FIPS disabled and DualStack disabled [42]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://kinesis.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isob-east-1 with FIPS enabled and DualStack disabled [43]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://kinesis-fips.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For custom endpoint with region set and fips disabled and dualstack disabled [44]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For custom endpoint with region not set and fips disabled and dualstack disabled [45]',
      () {
    final resolved = resolveEndpoint(
        useFips: false, useDualStack: false, endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For custom endpoint with fips enabled and dualstack disabled [46]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: true,
          useDualStack: false,
          endpoint: 'https://example.com'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: FIPS and custom endpoint are not supported')),
    );
  });
  test('For custom endpoint with fips disabled and dualstack enabled [47]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: true,
          endpoint: 'https://example.com'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: Dualstack and custom endpoint are not supported')),
    );
  });
  test('Missing region [48]', () {
    expect(
      () => resolveEndpoint(),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid Configuration: Missing Region')),
    );
  });
  test('Invalid ARN: Failed to parse ARN. [49]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          streamARN: 'arn'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Failed to parse ARN.')),
    );
  });
  test('Invalid ARN: partition missing from ARN. [50]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          streamARN: 'arn::kinesis:us-west-2:123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Failed to parse ARN.')),
    );
  });
  test('Invalid ARN: partitions mismatch. [51]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-gov-west-1',
          useFips: false,
          useDualStack: false,
          streamARN:
              'arn:aws:kinesis:us-west-2:123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Partition: aws from ARN doesn\'t match with partition name: aws-us-gov.')),
    );
  });
  test('Invalid ARN: Not Kinesis [52]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          streamARN: 'arn:aws:s3:us-west-2:123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: The ARN was not for the Kinesis service, found: s3.')),
    );
  });
  test('Invalid ARN: Region is missing in ARN [53]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          streamARN: 'arn:aws:kinesis::123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>()
          .having((e) => e.message, 'message', 'Invalid ARN: Invalid region.')),
    );
  });
  test('Invalid ARN: Region is empty string in ARN [54]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          streamARN: 'arn:aws:kinesis:  :123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>()
          .having((e) => e.message, 'message', 'Invalid ARN: Invalid region.')),
    );
  });
  test('Invalid ARN: Invalid account id [55]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          streamARN: 'arn:aws:kinesis:us-east-1::stream/testStream',
          operationType: 'control'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Invalid account id.')),
    );
  });
  test('Invalid ARN: Invalid account id [56]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          streamARN: 'arn:aws:kinesis:us-east-1:   :stream/testStream',
          operationType: 'control'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Invalid account id.')),
    );
  });
  test('Invalid ARN: Kinesis ARNs only support stream arn types [57]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          streamARN: 'arn:aws:kinesis:us-east-1:123:accesspoint/testStream'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: Kinesis ARNs don\'t support `accesspoint` arn types.')),
    );
  });
  test('OperationType not set [58]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          streamARN:
              'arn:aws:kinesis:us-east-1:123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Operation Type is not set. Please contact service team for resolution.')),
    );
  });
  test('Custom Endpoint is specified [59]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream',
        endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint targeting control operation type [60]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.control-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint targeting data operation type [61]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with fips targeting data operation type [62]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(
        resolved.url, 'https://123.data-kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with fips targeting control operation type [63]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url,
        'https://123.control-kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with Dual Stack and FIPS enabled [64]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: true,
        operationType: 'control',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.control-kinesis-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with Dual Stack enabled [65]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-1',
        useFips: false,
        useDualStack: true,
        operationType: 'data',
        streamARN: 'arn:aws:kinesis:us-west-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.data-kinesis.us-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with FIPS and DualStack disabled [66]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamARN: 'arn:aws:kinesis:us-west-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.control-kinesis.us-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('RegionMismatch: client region should be used for endpoint region [67]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        streamARN: 'arn:aws:kinesis:us-west-1:123:stream/testStream');
    expect(resolved.url, 'https://123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with FIPS enabled [68]', () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        streamARN: 'arn:aws-cn:kinesis:cn-northwest-1:123:stream/test-stream');
    expect(resolved.url,
        'https://123.data-kinesis-fips.cn-northwest-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with FIPS and DualStack enabled for cn regions. [69]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1',
        useFips: true,
        useDualStack: true,
        operationType: 'data',
        streamARN: 'arn:aws-cn:kinesis:cn-northwest-1:123:stream/test-stream');
    expect(resolved.url,
        'https://123.data-kinesis-fips.cn-northwest-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint targeting control operation type in ADC regions [70]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamARN: 'arn:aws-iso:kinesis:us-iso-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint targeting control operation type in ADC regions [71]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-west-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamARN: 'arn:aws-iso:kinesis:us-iso-west-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis.us-iso-west-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint targeting data operation type in ADC regions [72]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        streamARN:
            'arn:aws-iso-b:kinesis:us-isob-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Account endpoint with fips targeting control operation type in ADC regions [73]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        streamARN: 'arn:aws-iso:kinesis:us-iso-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis-fips.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Account endpoint with fips targeting data operation type in ADC regions [74]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        streamARN:
            'arn:aws-iso-b:kinesis:us-isob-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis-fips.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Invalid ConsumerARN: Failed to parse ARN. [75]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          consumerARN: 'arn'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Failed to parse ARN.')),
    );
  });
  test('Invalid ConsumerARN: partition missing from ARN. [76]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          consumerARN:
              'arn::kinesis:us-west-2:123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Failed to parse ARN.')),
    );
  });
  test('Invalid ARN: partitions mismatch. [77]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-gov-west-1',
          useFips: false,
          useDualStack: false,
          consumerARN:
              'arn:aws:kinesis:us-west-2:123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Partition: aws from ARN doesn\'t match with partition name: aws-us-gov.')),
    );
  });
  test('Invalid ARN: Not Kinesis [78]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          consumerARN:
              'arn:aws:s3:us-west-2:123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: The ARN was not for the Kinesis service, found: s3.')),
    );
  });
  test('Invalid ARN: Region is missing in ARN [79]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          consumerARN:
              'arn:aws:kinesis::123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>()
          .having((e) => e.message, 'message', 'Invalid ARN: Invalid region.')),
    );
  });
  test('Invalid ARN: Region is empty string in ARN [80]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          consumerARN:
              'arn:aws:kinesis:  :123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>()
          .having((e) => e.message, 'message', 'Invalid ARN: Invalid region.')),
    );
  });
  test('Invalid ARN: Invalid account id [81]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          consumerARN:
              'arn:aws:kinesis:us-east-1::stream/testStream/consumer/test-consumer:1525898737',
          operationType: 'control'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Invalid account id.')),
    );
  });
  test('Invalid ARN: Invalid account id [82]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          consumerARN:
              'arn:aws:kinesis:us-east-1:   :stream/testStream/consumer/test-consumer:1525898737',
          operationType: 'control'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Invalid account id.')),
    );
  });
  test(
      'Invalid ARN: Kinesis ARNs only support stream arn/consumer arn types [83]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          consumerARN:
              'arn:aws:kinesis:us-east-1:123:accesspoint/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: Kinesis ARNs don\'t support `accesspoint` arn types.')),
    );
  });
  test('OperationType not set [84]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          consumerARN:
              'arn:aws:kinesis:us-east-1:123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Operation Type is not set. Please contact service team for resolution.')),
    );
  });
  test('Custom Endpoint is specified [85]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        consumerARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737',
        endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint targeting control operation type [86]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        consumerARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.control-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint targeting data operation type [87]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        consumerARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with fips targeting data operation type [88]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        consumerARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(
        resolved.url, 'https://123.data-kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with fips targeting control operation type [89]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        consumerARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url,
        'https://123.control-kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with Dual Stack and FIPS enabled [90]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: true,
        operationType: 'control',
        consumerARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.control-kinesis-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with Dual Stack enabled [91]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-1',
        useFips: false,
        useDualStack: true,
        operationType: 'data',
        consumerARN:
            'arn:aws:kinesis:us-west-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.data-kinesis.us-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with FIPS and DualStack disabled [92]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        consumerARN:
            'arn:aws:kinesis:us-west-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.control-kinesis.us-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('RegionMismatch: client region should be used for endpoint region [93]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        consumerARN:
            'arn:aws:kinesis:us-west-1:123:stream/testStream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with FIPS enabled [94]', () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        consumerARN:
            'arn:aws-cn:kinesis:cn-northwest-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url,
        'https://123.data-kinesis-fips.cn-northwest-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint with FIPS and DualStack enabled for cn regions. [95]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1',
        useFips: true,
        useDualStack: true,
        operationType: 'data',
        consumerARN:
            'arn:aws-cn:kinesis:cn-northwest-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url,
        'https://123.data-kinesis-fips.cn-northwest-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint targeting control operation type in ADC regions [96]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        consumerARN:
            'arn:aws-iso:kinesis:us-iso-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://kinesis.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint targeting control operation type in ADC regions [97]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-west-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        consumerARN:
            'arn:aws-iso:kinesis:us-iso-west-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://kinesis.us-iso-west-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account endpoint targeting data operation type in ADC regions [98]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        consumerARN:
            'arn:aws-iso-b:kinesis:us-isob-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://kinesis.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Account endpoint with fips targeting control operation type in ADC regions [99]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        consumerARN:
            'arn:aws-iso:kinesis:us-iso-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://kinesis-fips.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Account endpoint with fips targeting data operation type in ADC regions [100]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        consumerARN:
            'arn:aws-iso-b:kinesis:us-isob-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://kinesis-fips.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('ConsumerARN targeting US-EAST-1 [101]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        consumerARN:
            'arn:aws:kinesis:us-east-1:123456789123:stream/foobar/consumer/test-consumer:1525898737');
    expect(resolved.url,
        'https://123456789123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Both StreamARN and ConsumerARN specified. StreamARN should take precedence [102]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/foobar',
        consumerARN:
            'arn:aws:kinesis:us-east-1:123456789123:stream/foobar/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('ResourceARN test: Invalid ARN: Failed to parse ARN. [103]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN: 'arn'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Failed to parse ARN.')),
    );
  });
  test(
      'ResourceARN as StreamARN test: Invalid ARN: partition missing from ARN. [104]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN: 'arn::kinesis:us-west-2:123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Failed to parse ARN.')),
    );
  });
  test('ResourceARN as StreamARN test: Invalid ARN: partitions mismatch. [105]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-gov-west-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn:aws:kinesis:us-west-2:123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Partition: aws from ARN doesn\'t match with partition name: aws-us-gov.')),
    );
  });
  test('ResourceARN as StreamARN test: Invalid ARN: Not Kinesis [106]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN: 'arn:aws:s3:us-west-2:123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: The ARN was not for the Kinesis service, found: s3.')),
    );
  });
  test(
      'ResourceARN as StreamARN test: Invalid ARN: Region is missing in ARN [107]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN: 'arn:aws:kinesis::123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>()
          .having((e) => e.message, 'message', 'Invalid ARN: Invalid region.')),
    );
  });
  test(
      'ResourceARN as StreamARN test: Invalid ARN: Region is empty string in ARN [108]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN: 'arn:aws:kinesis:  :123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>()
          .having((e) => e.message, 'message', 'Invalid ARN: Invalid region.')),
    );
  });
  test('ResourceARN as StreamARN test: Invalid ARN: Invalid account id [109]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN: 'arn:aws:kinesis:us-east-1::stream/testStream',
          operationType: 'control'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Invalid account id.')),
    );
  });
  test('ResourceARN as StreamARN test: Invalid ARN: Invalid account id [110]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN: 'arn:aws:kinesis:us-east-1:   :stream/testStream',
          operationType: 'control'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Invalid account id.')),
    );
  });
  test(
      'ResourceARN as StreamARN test: Invalid ARN: Kinesis ARNs only support stream arn types [111]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN: 'arn:aws:kinesis:us-east-1:123:accesspoint/testStream'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: Kinesis ARNs don\'t support `accesspoint` arn types.')),
    );
  });
  test('ResourceARN as StreamARN test: OperationType not set [112]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn:aws:kinesis:us-east-1:123456789012:stream/testStream'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Operation Type is not set. Please contact service team for resolution.')),
    );
  });
  test('ResourceARN as StreamARN test: Custom Endpoint is specified [113]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream',
        endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint targeting control operation type [114]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.control-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint targeting data operation type [115]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint with fips targeting data operation type [116]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(
        resolved.url, 'https://123.data-kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint with fips targeting control operation type [117]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url,
        'https://123.control-kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint with Dual Stack and FIPS enabled [118]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: true,
        operationType: 'control',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.control-kinesis-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint with Dual Stack enabled [119]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1',
        useFips: false,
        useDualStack: true,
        operationType: 'data',
        resourceARN: 'arn:aws:kinesis:us-west-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.data-kinesis.us-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint with FIPS and DualStack disabled [120]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        resourceARN: 'arn:aws:kinesis:us-west-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.control-kinesis.us-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: RegionMismatch: client region should be used for endpoint region [121]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        resourceARN: 'arn:aws:kinesis:us-west-1:123:stream/testStream');
    expect(resolved.url, 'https://123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint with FIPS enabled [122]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        resourceARN:
            'arn:aws-cn:kinesis:cn-northwest-1:123:stream/test-stream');
    expect(resolved.url,
        'https://123.data-kinesis-fips.cn-northwest-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint with FIPS and DualStack enabled for cn regions. [123]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1',
        useFips: true,
        useDualStack: true,
        operationType: 'data',
        resourceARN:
            'arn:aws-cn:kinesis:cn-northwest-1:123:stream/test-stream');
    expect(resolved.url,
        'https://123.data-kinesis-fips.cn-northwest-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint targeting control operation type in ADC regions [124]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        resourceARN:
            'arn:aws-iso:kinesis:us-iso-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint targeting control operation type in ADC regions [125]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-west-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        resourceARN:
            'arn:aws-iso:kinesis:us-iso-west-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis.us-iso-west-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint targeting data operation type in ADC regions [126]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        resourceARN:
            'arn:aws-iso-b:kinesis:us-isob-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint with fips targeting control operation type in ADC regions [127]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        resourceARN:
            'arn:aws-iso:kinesis:us-iso-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis-fips.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as StreamARN test: Account endpoint with fips targeting data operation type in ADC regions [128]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        resourceARN:
            'arn:aws-iso-b:kinesis:us-isob-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis-fips.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Invalid ARN: partition missing from ARN. [129]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn::kinesis:us-west-2:123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Failed to parse ARN.')),
    );
  });
  test(
      'ResourceARN as ConsumerARN test: Invalid ARN: partitions mismatch. [130]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-gov-west-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn:aws:kinesis:us-west-2:123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Partition: aws from ARN doesn\'t match with partition name: aws-us-gov.')),
    );
  });
  test('ResourceARN as ConsumerARN test: Invalid ARN: Not Kinesis [131]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn:aws:s3:us-west-2:123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: The ARN was not for the Kinesis service, found: s3.')),
    );
  });
  test(
      'ResourceARN as ConsumerARN test: Invalid ARN: Region is missing in ARN [132]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn:aws:kinesis::123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>()
          .having((e) => e.message, 'message', 'Invalid ARN: Invalid region.')),
    );
  });
  test(
      'ResourceARN as ConsumerARN test: Invalid ARN: Region is empty string in ARN [133]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn:aws:kinesis:  :123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>()
          .having((e) => e.message, 'message', 'Invalid ARN: Invalid region.')),
    );
  });
  test('ResourceARN as ConsumerARN test: Invalid ARN: Invalid account id [134]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn:aws:kinesis:us-east-1::stream/testStream/consumer/test-consumer:1525898737',
          operationType: 'control'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Invalid account id.')),
    );
  });
  test('ResourceARN as ConsumerARN test: Invalid ARN: Invalid account id [135]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn:aws:kinesis:us-east-1:   :stream/testStream/consumer/test-consumer:1525898737',
          operationType: 'control'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: Invalid account id.')),
    );
  });
  test(
      'ResourceARN as ConsumerARN test: Invalid ARN: Kinesis ARNs only support stream arn/consumer arn types [136]',
      () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn:aws:kinesis:us-east-1:123:accesspoint/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: Kinesis ARNs don\'t support `accesspoint` arn types.')),
    );
  });
  test('ResourceARN as ConsumerARN test: OperationType not set [137]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          resourceARN:
              'arn:aws:kinesis:us-east-1:123456789012:stream/testStream/consumer/test-consumer:1525898737'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Operation Type is not set. Please contact service team for resolution.')),
    );
  });
  test('ResourceARN as ConsumerARN test: Custom Endpoint is specified [138]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        resourceARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737',
        endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint targeting control operation type [139]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        resourceARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.control-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint targeting data operation type [140]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        resourceARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint with fips targeting data operation type [141]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        resourceARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(
        resolved.url, 'https://123.data-kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint with fips targeting control operation type [142]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        resourceARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url,
        'https://123.control-kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint with Dual Stack and FIPS enabled [143]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: true,
        operationType: 'control',
        resourceARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.control-kinesis-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint with Dual Stack enabled [144]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1',
        useFips: false,
        useDualStack: true,
        operationType: 'data',
        resourceARN:
            'arn:aws:kinesis:us-west-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.data-kinesis.us-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint with FIPS and DualStack disabled [145]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        resourceARN:
            'arn:aws:kinesis:us-west-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.control-kinesis.us-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: RegionMismatch: client region should be used for endpoint region [146]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        resourceARN:
            'arn:aws:kinesis:us-west-1:123:stream/testStream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint with FIPS enabled [147]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        resourceARN:
            'arn:aws-cn:kinesis:cn-northwest-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url,
        'https://123.data-kinesis-fips.cn-northwest-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint with FIPS and DualStack enabled for cn regions. [148]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1',
        useFips: true,
        useDualStack: true,
        operationType: 'data',
        resourceARN:
            'arn:aws-cn:kinesis:cn-northwest-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url,
        'https://123.data-kinesis-fips.cn-northwest-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint targeting control operation type in ADC regions [149]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        resourceARN:
            'arn:aws-iso:kinesis:us-iso-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://kinesis.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint targeting control operation type in ADC regions [150]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-west-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        resourceARN:
            'arn:aws-iso:kinesis:us-iso-west-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://kinesis.us-iso-west-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint targeting data operation type in ADC regions [151]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        resourceARN:
            'arn:aws-iso-b:kinesis:us-isob-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://kinesis.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint with fips targeting control operation type in ADC regions [152]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        resourceARN:
            'arn:aws-iso:kinesis:us-iso-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://kinesis-fips.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ResourceARN as ConsumerARN test: Account endpoint with fips targeting data operation type in ADC regions [153]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        resourceARN:
            'arn:aws-iso-b:kinesis:us-isob-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url, 'https://kinesis-fips.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: OperationType not set with StreamId [154]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: false,
          streamId: 'af4lwng4k01746835071-xyz'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Operation Type is not set. Please contact service team for resolution.')),
    );
  });
  test('StreamId test: Stream endpoint targeting control operation type [155]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Stream endpoint targeting data operation type [156]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint with fips targeting data operation type [157]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint with fips targeting control operation type [158]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Stream endpoint with Dual Stack and FIPS enabled [159]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: true,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        streamARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Stream endpoint with Dual Stack enabled [160]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-1',
        useFips: false,
        useDualStack: true,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        streamARN: 'arn:aws:kinesis:us-west-1:123:stream/test-stream');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis.us-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Stream endpoint with FIPS and DualStack disabled [161]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        streamARN: 'arn:aws:kinesis:us-west-1:123:stream/test-stream');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis.us-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint FIPS and DualStack disabled with endpoint [162]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint targeting data operation type with endpoint [163]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint with fips targeting data operation type with endpoint [164]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis-pod1-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint with fips targeting control operation type with endpoint [165]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis-pod1-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint with Dual Stack and FIPS enabled with endpoint [166]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: true,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis-pod1-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint with Dual Stack enabled with endpoint [167]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: true,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis-pod1.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint targeting data operation type with https endpoint [168]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'https://kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: HTTPS endpoint with FIPS enabled targeting control operation type [169]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'https://kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis-pod1-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: HTTPS endpoint with FIPS enabled targeting data operation type [170]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'https://kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis-pod1-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: HTTPS endpoint with DualStack enabled targeting control operation type [171]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: true,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'https://kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis-pod1.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: HTTPS endpoint with DualStack enabled targeting data operation type [172]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: true,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'https://kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis-pod1.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: HTTPS endpoint with FIPS and DualStack enabled targeting control operation type [173]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: true,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'https://kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis-pod1-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: HTTPS endpoint with FIPS and DualStack enabled targeting data operation type [174]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: true,
        useDualStack: true,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'https://kinesis-pod1.us-east-1.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis-pod1-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: HTTPS endpoint with FIPS enabled in different region [175]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-2',
        useFips: true,
        useDualStack: false,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'https://kinesis-pod2.us-west-2.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis-pod2-fips.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: HTTPS endpoint with DualStack enabled in different region [176]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-2',
        useFips: false,
        useDualStack: true,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        endpoint: 'https://kinesis-pod2.us-west-2.amazonaws.com');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis-pod2.us-west-2.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint with ConsumerARN targeting control operation type [177]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        consumerARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint with ConsumerARN targeting data operation type [178]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        consumerARN:
            'arn:aws:kinesis:us-east-1:123:stream/test-stream/consumer/test-consumer:1525898737');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint with ResourceARN targeting control operation type [179]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-xyz',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.control-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'StreamId test: Stream endpoint with ResourceARN targeting data operation type [180]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071-xyz',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url,
        'https://af4lwng4k01746835071.xyz.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Invalid StreamId with ARN [181]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        operationType: 'data',
        streamId: 'af4lwng4k01746835071=xyz',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.data-kinesis.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Invalid streamId with custom endpoint [182]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-2',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071=xyz',
        endpoint: 'https://kinesis-pod2.us-west-2.amazonaws.com');
    expect(resolved.url, 'https://kinesis-pod2.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Invalid streamId [183]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-2',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071=xyz');
    expect(resolved.url, 'https://kinesis.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Invalid streamId with custom endpoint and ARN [184]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-2',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071=xyz',
        endpoint: 'https://kinesis-pod2.us-west-2.amazonaws.com',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://kinesis-pod2.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Invalid streamId with longer prefix [185]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-2',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k0174683507123-xyz',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.control-kinesis.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Invalid streamId with shorter prefix [186]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-2',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835-xyz',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.control-kinesis.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Invalid streamId with longer suffix [187]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-2',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-wxyz',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.control-kinesis.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('StreamId test: Invalid streamId with shorter suffix [188]', () {
    final resolved = resolveEndpoint(
        region: 'us-west-2',
        useFips: false,
        useDualStack: false,
        operationType: 'control',
        streamId: 'af4lwng4k01746835071-yz',
        resourceARN: 'arn:aws:kinesis:us-east-1:123:stream/test-stream');
    expect(resolved.url, 'https://123.control-kinesis.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
}
