// AUTO-GENERATED: This file is generated by the `generator` package.
//
// Endpoint resolution conformance tests, derived from the service's
// `smithy.rules#endpointTests` trait.

// ignore_for_file: prefer_single_quotes, prefer_collection_literals, unnecessary_lambdas, unused_import

import 'package:aws_client/src/generated/sso_oidc/v2019_06_10.endpoints.dart';
import 'package:aws_client/src/shared/src/protocol/endpoints/endpoint_resolver.dart';
import 'package:test/test.dart';

void main() {
  test('For region ap-east-1 with FIPS disabled and DualStack disabled [0]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.ap-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-northeast-1 with FIPS disabled and DualStack disabled [1]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-northeast-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.ap-northeast-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-northeast-2 with FIPS disabled and DualStack disabled [2]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-northeast-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.ap-northeast-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-northeast-3 with FIPS disabled and DualStack disabled [3]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-northeast-3', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.ap-northeast-3.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ap-south-1 with FIPS disabled and DualStack disabled [4]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-south-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.ap-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-southeast-1 with FIPS disabled and DualStack disabled [5]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-southeast-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.ap-southeast-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-southeast-2 with FIPS disabled and DualStack disabled [6]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-southeast-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.ap-southeast-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ca-central-1 with FIPS disabled and DualStack disabled [7]',
      () {
    final resolved = resolveEndpoint(
        region: 'ca-central-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.ca-central-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-central-1 with FIPS disabled and DualStack disabled [8]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-central-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.eu-central-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-north-1 with FIPS disabled and DualStack disabled [9]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-north-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.eu-north-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-south-1 with FIPS disabled and DualStack disabled [10]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-south-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.eu-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-1 with FIPS disabled and DualStack disabled [11]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.eu-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-2 with FIPS disabled and DualStack disabled [12]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.eu-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-3 with FIPS disabled and DualStack disabled [13]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-3', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.eu-west-3.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region me-south-1 with FIPS disabled and DualStack disabled [14]',
      () {
    final resolved = resolveEndpoint(
        region: 'me-south-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.me-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region sa-east-1 with FIPS disabled and DualStack disabled [15]',
      () {
    final resolved = resolveEndpoint(
        region: 'sa-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.sa-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack disabled [16]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-2 with FIPS disabled and DualStack disabled [17]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-2 with FIPS disabled and DualStack disabled [18]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS enabled and DualStack enabled [19]', () {
    final resolved =
        resolveEndpoint(region: 'us-east-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://oidc-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS enabled and DualStack disabled [20]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://oidc-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack enabled [21]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://oidc.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS enabled and DualStack enabled [22]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: true, useDualStack: true);
    expect(resolved.url,
        'https://oidc-fips.cn-north-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS enabled and DualStack disabled [23]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://oidc-fips.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS disabled and DualStack enabled [24]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: false, useDualStack: true);
    expect(
        resolved.url, 'https://oidc.cn-north-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS disabled and DualStack disabled [25]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-gov-east-1 with FIPS disabled and DualStack disabled [26]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-gov-west-1 with FIPS disabled and DualStack disabled [27]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.us-gov-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS enabled and DualStack enabled [28]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://oidc-fips.us-gov-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS enabled and DualStack disabled [29]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://oidc.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS disabled and DualStack enabled [30]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://oidc.us-gov-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-iso-east-1 with FIPS enabled and DualStack disabled [31]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://oidc-fips.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-iso-east-1 with FIPS disabled and DualStack disabled [32]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isob-east-1 with FIPS enabled and DualStack disabled [33]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://oidc-fips.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isob-east-1 with FIPS disabled and DualStack disabled [34]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://oidc.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For custom endpoint with region set and fips disabled and dualstack disabled [35]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For custom endpoint with region not set and fips disabled and dualstack disabled [36]',
      () {
    final resolved = resolveEndpoint(
        useFips: false, useDualStack: false, endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For custom endpoint with fips enabled and dualstack disabled [37]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: true,
          useDualStack: false,
          endpoint: 'https://example.com'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: FIPS and custom endpoint are not supported')),
    );
  });
  test('For custom endpoint with fips disabled and dualstack enabled [38]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: true,
          endpoint: 'https://example.com'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: Dualstack and custom endpoint are not supported')),
    );
  });
  test('Missing region [39]', () {
    expect(
      () => resolveEndpoint(),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid Configuration: Missing Region')),
    );
  });
}
