name: all_apis
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  shared_aws_api:
    path: ../shared_aws_api

dev_dependencies:
  build_runner:
  json_serializable: ^3.3.0
  test: ^1.14.2


