name: all_apis
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shared_aws_api:
    path: ../shared_aws_api
  aws_credential_providers:
    path: ../aws_credential_providers

dev_dependencies:
  test: ^1.16.8

dependency_overrides:
  shared_aws_api:
    path: ../shared_aws_api