// AUTO-GENERATED: This file is generated by the `generator` package.
//
// Endpoint resolution conformance tests, derived from the service's
// `smithy.rules#endpointTests` trait.

// ignore_for_file: prefer_single_quotes, prefer_collection_literals, unnecessary_lambdas, unused_import

import 'package:aws_client/src/generated/iot_managed_integrations/v2025_03_03.endpoints.dart';
import 'package:aws_client/src/shared/src/protocol/endpoints/endpoint_resolver.dart';
import 'package:test/test.dart';

void main() {
  test('For custom endpoint with region not set and fips disabled [0]', () {
    final resolved =
        resolveEndpoint(endpoint: 'https://example.com', useFips: false);
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For custom endpoint with fips enabled [1]', () {
    expect(
      () => resolveEndpoint(endpoint: 'https://example.com', useFips: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: FIPS and custom endpoint are not supported')),
    );
  });
  test('For region us-east-1 with FIPS enabled and DualStack enabled [2]', () {
    final resolved = resolveEndpoint(region: 'us-east-1', useFips: true);
    expect(resolved.url,
        'https://api.iotmanagedintegrations-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack enabled [3]', () {
    final resolved = resolveEndpoint(region: 'us-east-1', useFips: false);
    expect(
        resolved.url, 'https://api.iotmanagedintegrations.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-northwest-1 with FIPS enabled and DualStack enabled [4]',
      () {
    final resolved = resolveEndpoint(region: 'cn-northwest-1', useFips: true);
    expect(resolved.url,
        'https://api.iotmanagedintegrations-fips.cn-northwest-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-northwest-1 with FIPS disabled and DualStack enabled [5]',
      () {
    final resolved = resolveEndpoint(region: 'cn-northwest-1', useFips: false);
    expect(resolved.url,
        'https://api.iotmanagedintegrations.cn-northwest-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-west-1 with FIPS enabled and DualStack enabled [6]',
      () {
    final resolved = resolveEndpoint(region: 'us-gov-west-1', useFips: true);
    expect(resolved.url,
        'https://api.iotmanagedintegrations-fips.us-gov-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-west-1 with FIPS disabled and DualStack enabled [7]',
      () {
    final resolved = resolveEndpoint(region: 'us-gov-west-1', useFips: false);
    expect(resolved.url,
        'https://api.iotmanagedintegrations.us-gov-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Missing region [8]', () {
    expect(
      () => resolveEndpoint(),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid Configuration: Missing Region')),
    );
  });
}
