// AUTO-GENERATED: This file is generated by the `generator` package.
//
// Endpoint resolution conformance tests, derived from the service's
// `smithy.rules#endpointTests` trait.

// ignore_for_file: prefer_single_quotes, prefer_collection_literals, unnecessary_lambdas, unused_import

import 'package:aws_client/src/generated/s3_control/v2018_08_20.endpoints.dart';
import 'package:aws_client/src/shared/src/protocol/endpoints/endpoint_resolver.dart';
import 'package:test/test.dart';

void main() {
  test('Vanilla outposts without ARN region + access point ARN@us-west-2 [0]',
      () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('Vanilla outposts with ARN region + access point ARN@us-west-2 [1]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:us-east-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('accept an access point ARN@us-west-2 [2]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('vanilla outposts china@cn-north-1 [3]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws-cn:s3-outposts:cn-north-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'cn-north-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'cn-north-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('gov region@us-west-2 [4]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('gov cloud with fips@us-west-2 [5]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(resolved.url, 'https://s3-outposts-fips.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('govcloud with fips + arn region@us-gov-west-1 [6]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws-us-gov:s3-outposts:us-gov-east-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-gov-west-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(
        resolved.url, 'https://s3-outposts-fips.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('gov region@cn-north-1 [7]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws-cn:s3-outposts:cn-north-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'cn-north-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'cn-north-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('gov cloud with fips@cn-north-1 [8]', () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws-cn:s3-outposts:cn-north-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
          accountId: '123456789012',
          region: 'cn-north-1',
          requiresAccountId: true,
          useDualStack: false,
          useFips: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Partition does not support FIPS')),
    );
  });
  test('govcloud with fips + arn region@us-gov-west-1 [9]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws-us-gov:s3-outposts:us-gov-east-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-gov-west-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(
        resolved.url, 'https://s3-outposts-fips.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('gov region@af-south-1 [10]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:af-south-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'af-south-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.af-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'af-south-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('gov cloud with fips@af-south-1 [11]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:af-south-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'af-south-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(resolved.url, 'https://s3-outposts-fips.af-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'af-south-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('govcloud with fips + arn region@us-gov-west-1 [12]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws-us-gov:s3-outposts:us-gov-east-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-gov-west-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(
        resolved.url, 'https://s3-outposts-fips.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('CreateBucket + OutpostId = outposts endpoint@us-east-2 [13]', () {
    final resolved = resolveEndpoint(
        bucket: 'blah',
        outpostId: '123',
        region: 'us-east-2',
        requiresAccountId: false,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('CreateBucket + OutpostId with fips = outposts endpoint@us-east-2 [14]',
      () {
    final resolved = resolveEndpoint(
        bucket: 'blah',
        outpostId: '123',
        region: 'us-east-2',
        requiresAccountId: false,
        useDualStack: false,
        useFips: true);
    expect(resolved.url, 'https://s3-outposts-fips.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('CreateBucket without OutpostId = regular endpoint@us-east-2 [15]', () {
    final resolved = resolveEndpoint(
        bucket: 'blah',
        region: 'us-east-2',
        requiresAccountId: false,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-control.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('ListRegionalBuckets + OutpostId = outposts endpoint@us-east-2 [16]',
      () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        outpostId: 'op-123',
        region: 'us-east-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ListRegionalBuckets without OutpostId = regular endpoint@us-east-2 [17]',
      () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        region: 'us-east-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url,
        'https://123456789012.s3-control.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'ListRegionalBucket + OutpostId with fips = outposts endpoint@us-east-2 [18]',
      () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        outpostId: 'op-123',
        region: 'us-east-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(resolved.url, 'https://s3-outposts-fips.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('outpost access points support dualstack@us-west-2 [19]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: true,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-west-2.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('outpost access points support dualstack@af-south-1 [20]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:af-south-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'af-south-1',
        requiresAccountId: true,
        useDualStack: true,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.af-south-1.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'af-south-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('outpost access points support fips + dualstack@af-south-1 [21]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:af-south-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'af-south-1',
        requiresAccountId: true,
        useDualStack: true,
        useFips: true);
    expect(resolved.url, 'https://s3-outposts-fips.af-south-1.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'af-south-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('invalid ARN: must be include outpost ID@us-west-2 [22]', () {
    expect(
      () => resolveEndpoint(
          accessPointName: 'arn:aws:s3-outposts:us-west-2:123456789012:outpost',
          accountId: '123456789012',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid ARN: The Outpost Id was not set')),
    );
  });
  test('invalid ARN: must specify access point@us-west-2 [23]', () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid ARN: Expected a 4-component resource')),
    );
  });
  test('invalid ARN@us-west-2 [24]', () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws:s3-outposts:us-west-2:123456789012:outpost:myaccesspoint',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid ARN: Expected a 4-component resource')),
    );
  });
  test('when set, AccountId drives AP construction@us-west-2 [25]', () {
    final resolved = resolveEndpoint(
        accessPointName: 'myaccesspoint',
        accountId: 'myid-1234',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(
        resolved.url, 'https://myid-1234.s3-control.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Account ID set inline and in ARN but they both match@us-west-2 [26]',
      () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-west-2',
        requiresAccountId: true,
        useArnRegion: false,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('Account ID set inline and in ARN and they do not match@us-west-2 [27]',
      () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
          accountId: '999999999999',
          region: 'us-west-2',
          requiresAccountId: true,
          useArnRegion: false,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: the accountId specified in the ARN (`123456789012`) does not match the parameter (`999999999999`)')),
    );
  });
  test(
      'get access point prefixed with account id using endpoint url@us-west-2 [28]',
      () {
    final resolved = resolveEndpoint(
        accessPointName: 'apname',
        accountId: '123456789012',
        endpoint:
            'https://control.vpce-1a2b3c4d-5e6f.s3.us-west-2.vpce.amazonaws.com',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url,
        'https://123456789012.control.vpce-1a2b3c4d-5e6f.s3.us-west-2.vpce.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('endpoint url with s3-outposts@us-west-2 [29]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        endpoint: 'https://beta.example.com',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://beta.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('access point name with a bucket arn@us-west-2 [30]', () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:bucket:mybucket',
          endpoint: 'beta.example.com',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Expected an outpost type `accesspoint`, found `bucket`')),
    );
  });
  test('bucket arn with access point name@us-west-2 [31]', () {
    expect(
      () => resolveEndpoint(
          bucket:
              'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
          endpoint: 'beta.example.com',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: Expected an outpost type `bucket`, found `accesspoint`')),
    );
  });
  test('create bucket with outposts@us-west-2 [32]', () {
    final resolved = resolveEndpoint(
        bucket: 'bucketname',
        endpoint: 'https://beta.example.com',
        outpostId: 'op-123',
        region: 'us-west-2',
        requiresAccountId: false,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://beta.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('get bucket with endpoint_url@us-west-2 [33]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        endpoint: 'https://beta.example.com',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://beta.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('ListRegionalBucket + OutpostId endpoint url@us-east-2 [34]', () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        endpoint: 'https://beta.example.com',
        outpostId: 'op-123',
        region: 'us-east-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://beta.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('ListRegionalBucket + OutpostId + fips + endpoint url@us-east-2 [35]',
      () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        endpoint: 'https://beta.example.com',
        outpostId: 'op-123',
        region: 'us-east-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(resolved.url, 'https://beta.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('ListRegionalBucket + OutpostId + fips + dualstack@us-east-2 [36]', () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        outpostId: 'op-123',
        region: 'us-east-2',
        requiresAccountId: true,
        useDualStack: true,
        useFips: true);
    expect(resolved.url, 'https://s3-outposts-fips.us-east-2.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('CreateBucket + OutpostId endpoint url@us-east-2 [37]', () {
    final resolved = resolveEndpoint(
        bucket: 'blah',
        endpoint: 'https://beta.example.com',
        outpostId: '123',
        region: 'us-east-2',
        requiresAccountId: false,
        useDualStack: false,
        useFips: true);
    expect(resolved.url, 'https://beta.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'dualstack cannot be used with outposts when an endpoint URL is set@us-west-2. [38]',
      () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
          endpoint: 'https://s3-outposts.us-west-2.api.aws',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: true,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: DualStack and custom endpoint are not supported')),
    );
  });
  test('vanilla bucket arn requires account id@us-west-2 [39]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test(
      'bucket arn with UseArnRegion = true (arn region supercedes client configured region)@us-west-2 [40]',
      () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-east-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('bucket ARN in gov partition (non-fips)@us-gov-east-1 [41]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws-us-gov:s3-outposts:us-gov-east-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-gov-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('bucket ARN in gov partition with FIPS@us-gov-west-1 [42]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws-us-gov:s3-outposts:us-gov-west-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-gov-west-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(
        resolved.url, 'https://s3-outposts-fips.us-gov-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-west-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('bucket ARN in aws partition with FIPS@us-east-2 [43]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-east-2:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-east-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(resolved.url, 'https://s3-outposts-fips.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('bucket ARN in aws partition with fips + dualstack@us-east-2 [44]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-east-2:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-east-2',
        requiresAccountId: true,
        useDualStack: true,
        useFips: true);
    expect(resolved.url, 'https://s3-outposts-fips.us-east-2.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('vanilla bucket arn requires account id@cn-north-1 [45]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws-cn:s3-outposts:cn-north-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'cn-north-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'cn-north-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test(
      'bucket arn with UseArnRegion = true (arn region supercedes client configured region)@us-west-2 [46]',
      () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-east-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('bucket ARN in gov partition (non-fips)@us-gov-east-1 [47]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws-us-gov:s3-outposts:us-gov-east-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-gov-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('bucket ARN in gov partition with FIPS@us-gov-west-1 [48]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws-us-gov:s3-outposts:us-gov-west-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-gov-west-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(
        resolved.url, 'https://s3-outposts-fips.us-gov-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-west-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('bucket ARN in aws partition with FIPS@us-east-2 [49]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-east-2:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-east-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(resolved.url, 'https://s3-outposts-fips.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('Outposts support dualstack @us-west-2 [50]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: true,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-west-2.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('vanilla bucket arn requires account id@af-south-1 [51]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:af-south-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'af-south-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.af-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'af-south-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test(
      'bucket arn with UseArnRegion = true (arn region supercedes client configured region)@us-west-2 [52]',
      () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-east-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('bucket ARN in gov partition (non-fips)@us-gov-east-1 [53]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws-us-gov:s3-outposts:us-gov-east-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-gov-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('bucket ARN in gov partition with FIPS@us-gov-west-1 [54]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws-us-gov:s3-outposts:us-gov-west-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-gov-west-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(
        resolved.url, 'https://s3-outposts-fips.us-gov-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-west-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('bucket ARN in aws partition with FIPS@us-east-2 [55]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-east-2:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-east-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(resolved.url, 'https://s3-outposts-fips.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('Invalid ARN: missing outpost id and bucket@us-west-2 [56]', () {
    expect(
      () => resolveEndpoint(
          bucket: 'arn:aws:s3-outposts:us-west-2:123456789012:outpost',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid ARN: The Outpost Id was not set')),
    );
  });
  test('Invalid ARN: missing bucket@us-west-2 [57]', () {
    expect(
      () => resolveEndpoint(
          bucket:
              'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid ARN: Expected a 4-component resource')),
    );
  });
  test('Invalid ARN: missing outpost and bucket ids@us-west-2 [58]', () {
    expect(
      () => resolveEndpoint(
          bucket: 'arn:aws:s3-outposts:us-west-2:123456789012:outpost:bucket',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid ARN: Expected a 4-component resource')),
    );
  });
  test('Invalid ARN: missing bucket id@us-west-2 [59]', () {
    expect(
      () => resolveEndpoint(
          bucket:
              'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:bucket',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: expected a bucket name')),
    );
  });
  test('account id inserted into hostname@us-west-2 [60]', () {
    final resolved = resolveEndpoint(
        accountId: '1234567890',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(
        resolved.url, 'https://1234567890.s3-control.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('account id prefix with dualstack@us-east-1 [61]', () {
    final resolved = resolveEndpoint(
        accountId: '1234567890',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: true,
        useFips: false);
    expect(resolved.url,
        'https://1234567890.s3-control.dualstack.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('account id prefix with fips@us-east-1 [62]', () {
    final resolved = resolveEndpoint(
        accountId: '1234567890',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(resolved.url,
        'https://1234567890.s3-control-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('custom account id prefix with fips@us-east-1 [63]', () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(resolved.url,
        'https://123456789012.s3-control-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('standard url @ us-east-1 [64]', () {
    final resolved = resolveEndpoint(region: 'us-east-1');
    expect(resolved.url, 'https://s3-control.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('fips url @ us-east-1 [65]', () {
    final resolved = resolveEndpoint(region: 'us-east-1', useFips: true);
    expect(resolved.url, 'https://s3-control-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('dualstack url @ us-east-1 [66]', () {
    final resolved = resolveEndpoint(region: 'us-east-1', useDualStack: true);
    expect(
        resolved.url, 'https://s3-control.dualstack.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('fips,dualstack url @ us-east-1 [67]', () {
    final resolved =
        resolveEndpoint(region: 'us-east-1', useDualStack: true, useFips: true);
    expect(resolved.url,
        'https://s3-control-fips.dualstack.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('standard url @ cn-north-1 [68]', () {
    final resolved = resolveEndpoint(region: 'cn-north-1');
    expect(resolved.url, 'https://s3-control.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'cn-north-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('fips @ cn-north-1 [69]', () {
    expect(
      () => resolveEndpoint(
          region: 'cn-north-1', useDualStack: true, useFips: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Partition does not support FIPS')),
    );
  });
  test('custom account id prefix @us-east-1 [70]', () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url,
        'https://123456789012.s3-control.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('invalid account id prefix @us-east-1 [71]', () {
    expect(
      () => resolveEndpoint(
          accountId: '/?invalid&not-host*label',
          region: 'us-east-1',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'AccountId must only contain a-z, A-Z, 0-9 and `-`.')),
    );
  });
  test('custom account id prefix with fips@us-east-1 [72]', () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(resolved.url,
        'https://123456789012.s3-control-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('custom account id prefix with dualstack,fips@us-east-1 [73]', () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: true,
        useFips: true);
    expect(resolved.url,
        'https://123456789012.s3-control-fips.dualstack.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('custom account id with custom endpoint [74]', () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        region: 'us-east-1',
        requiresAccountId: true,
        endpoint: 'https://example.com');
    expect(resolved.url, 'https://123456789012.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('RequiresAccountId with AccountId unset [75]', () {
    expect(
      () => resolveEndpoint(region: 'us-east-1', requiresAccountId: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'AccountId is required but not set')),
    );
  });
  test('RequiresAccountId with AccountId unset and custom endpoint [76]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          endpoint: 'https://beta.example.com',
          requiresAccountId: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'AccountId is required but not set')),
    );
  });
  test('RequiresAccountId with invalid AccountId and custom endpoint [77]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          endpoint: 'https://beta.example.com',
          accountId: '/?invalid&not-host*label',
          requiresAccountId: true),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'AccountId must only contain a-z, A-Z, 0-9 and `-`.')),
    );
  });
  test('account id with custom endpoint, fips [78]', () {
    final resolved = resolveEndpoint(
        accountId: '123456789012',
        region: 'us-east-1',
        requiresAccountId: true,
        endpoint: 'https://example.com',
        useFips: true);
    expect(resolved.url, 'https://123456789012.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('custom endpoint, fips [79]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', endpoint: 'https://example.com', useFips: true);
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('custom endpoint, fips [80]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', endpoint: 'https://example.com', useFips: true);
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('custom endpoint, DualStack [81]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          endpoint: 'https://example.com',
          useFips: false,
          useDualStack: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: DualStack and custom endpoint are not supported')),
    );
  });
  test('region not set [82]', () {
    expect(
      () => resolveEndpoint(),
      throwsA(isA<EndpointResolutionException>()
          .having((e) => e.message, 'message', 'Region must be set')),
    );
  });
  test('invalid partition [83]', () {
    expect(
      () => resolveEndpoint(region: 'invalid-region 42'),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid region: region was not a valid DNS name.')),
    );
  });
  test('ListRegionalBuckets + OutpostId without accountId set. [84]', () {
    expect(
      () => resolveEndpoint(
          outpostId: 'op-123',
          region: 'us-east-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'AccountId is required but not set')),
    );
  });
  test('ListRegionalBuckets + OutpostId with invalid accountId set. [85]', () {
    expect(
      () => resolveEndpoint(
          accountId: '/?invalid&not-host*label',
          outpostId: 'op-123',
          region: 'us-east-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'AccountId must only contain a-z, A-Z, 0-9 and `-`.')),
    );
  });
  test('accesspoint set but missing accountId [86]', () {
    expect(
      () => resolveEndpoint(
          accessPointName: 'myaccesspoint',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'AccountId is required but not set')),
    );
  });
  test('outpost accesspoint ARN with missing accountId [87]', () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws:s3-outposts:us-west-2::outpost:op-01234567890123456:outpost:op1',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: missing account ID')),
    );
  });
  test('bucket ARN with missing accountId [88]', () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws:s3-outposts:us-west-2::outpost:op-01234567890123456:bucket:mybucket',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Invalid ARN: missing account ID')),
    );
  });
  test('endpoint url with accesspoint (non-arn) [89]', () {
    final resolved = resolveEndpoint(
        accessPointName: 'apname',
        endpoint: 'https://beta.example.com',
        accountId: '123456789012',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://123456789012.beta.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('access point name with an accesspoint arn@us-west-2 [90]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        endpoint: 'https://beta.example.com',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://beta.example.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('DualStack + Custom endpoint is not supported(non-arn) [91]', () {
    expect(
      () => resolveEndpoint(
          accessPointName: 'apname',
          endpoint: 'https://beta.example.com',
          accountId: '123456789012',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: true,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: DualStack and custom endpoint are not supported')),
    );
  });
  test(
      'get bucket with custom endpoint and dualstack is not supported@us-west-2 [92]',
      () {
    expect(
      () => resolveEndpoint(
          bucket:
              'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:bucket:mybucket',
          endpoint: 'https://s3-outposts.us-west-2.api.aws',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: true,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: DualStack and custom endpoint are not supported')),
    );
  });
  test('ListRegionalBuckets + OutpostId with fips in CN. [93]', () {
    expect(
      () => resolveEndpoint(
          accountId: '012345678912',
          outpostId: 'op-123',
          region: 'cn-north-1',
          requiresAccountId: true,
          useDualStack: false,
          useFips: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Partition does not support FIPS')),
    );
  });
  test('ListRegionalBuckets + invalid OutpostId. [94]', () {
    expect(
      () => resolveEndpoint(
          accountId: '012345678912',
          outpostId: '?outpost/invalid+',
          region: 'us-west-1',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'OutpostId must only contain a-z, A-Z, 0-9 and `-`.')),
    );
  });
  test('bucket ARN with mismatched accountId [95]', () {
    expect(
      () => resolveEndpoint(
          bucket:
              'arn:aws:s3-outposts:us-west-2:999999:outpost:op-01234567890123456:bucket:mybucket',
          accountId: '012345678912',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid ARN: the accountId specified in the ARN (`999999`) does not match the parameter (`012345678912`)')),
    );
  });
  test('OutpostId with invalid region [96]', () {
    expect(
      () => resolveEndpoint(
          outpostId: 'op-123',
          region: 'invalid-region 42',
          accountId: '0123456',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid region: region was not a valid DNS name.')),
    );
  });
  test('OutpostId with RequireAccountId unset [97]', () {
    final resolved = resolveEndpoint(
        outpostId: 'op-123',
        region: 'us-west-2',
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Outpost Accesspoint ARN with arn region and client region mismatch with UseArnRegion=false [98]',
      () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws:s3-outposts:us-east-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
          accountId: '123456789012',
          region: 'us-west-2',
          requiresAccountId: true,
          useArnRegion: false,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid configuration: region from ARN `us-east-1` does not match client region `us-west-2` and UseArnRegion is `false`')),
    );
  });
  test(
      'Outpost Bucket ARN with arn region and client region mismatch with UseArnRegion=false [99]',
      () {
    expect(
      () => resolveEndpoint(
          bucket:
              'arn:aws:s3-outposts:us-east-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
          endpoint: 'https://beta.example.com',
          region: 'us-west-2',
          requiresAccountId: true,
          useArnRegion: false,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid configuration: region from ARN `us-east-1` does not match client region `us-west-2` and UseArnRegion is `false`')),
    );
  });
  test('Accesspoint ARN with region mismatch and UseArnRegion unset [100]', () {
    final resolved = resolveEndpoint(
        accessPointName:
            'arn:aws:s3-outposts:us-east-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
        accountId: '123456789012',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('Bucket ARN with region mismatch and UseArnRegion unset [101]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-east-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test(
      'Outpost Bucket ARN with partition mismatch with UseArnRegion=true [102]',
      () {
    expect(
      () => resolveEndpoint(
          bucket:
              'arn:aws:s3-outposts:cn-north-1:123456789012:outpost:op-01234567890123456:bucket:mybucket',
          region: 'us-west-2',
          requiresAccountId: true,
          useArnRegion: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Client was configured for partition `aws` but ARN has `aws-cn`')),
    );
  });
  test('Accesspoint ARN with partition mismatch and UseArnRegion=true [103]',
      () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws:s3-outposts:cn-north-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
          accountId: '123456789012',
          region: 'us-west-2',
          requiresAccountId: true,
          useDualStack: false,
          useArnRegion: true,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Client was configured for partition `aws` but ARN has `aws-cn`')),
    );
  });
  test(
      'Accesspoint ARN with region mismatch, UseArnRegion=false and custom endpoint [104]',
      () {
    expect(
      () => resolveEndpoint(
          accessPointName:
              'arn:aws:s3-outposts:cn-north-1:123456789012:outpost:op-01234567890123456:accesspoint:myaccesspoint',
          region: 'us-west-2',
          endpoint: 'https://example.com',
          requiresAccountId: true,
          useDualStack: false,
          useArnRegion: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid configuration: region from ARN `cn-north-1` does not match client region `us-west-2` and UseArnRegion is `false`')),
    );
  });
  test('outpost bucket arn@us-west-2 [105]', () {
    final resolved = resolveEndpoint(
        bucket:
            'arn:aws:s3-outposts:us-west-2:123456789012:outpost:op-01234567890123456:bucket:mybucket',
        region: 'us-west-2',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3-outposts.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3-outposts');
    expect(resolved.authSchemes[0].signingRegion, 'us-west-2');
    expect(resolved.headers.keys.toSet(),
        ['x-amz-account-id', 'x-amz-outpost-id'].toSet());
    expect(resolved.headers['x-amz-account-id'], ['123456789012']);
    expect(resolved.headers['x-amz-outpost-id'], ['op-01234567890123456']);
  });
  test('S3 Snow Control with bucket [106]', () {
    final resolved = resolveEndpoint(
        region: 'snow',
        bucket: 'bucketName',
        endpoint: 'https://10.0.1.12:433',
        useFips: false,
        useDualStack: false);
    expect(resolved.url, 'https://10.0.1.12:433');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'snow');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('S3 Snow Control without bucket [107]', () {
    final resolved = resolveEndpoint(
        region: 'snow',
        endpoint: 'https://10.0.1.12:433',
        useFips: false,
        useDualStack: false);
    expect(resolved.url, 'https://10.0.1.12:433');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'snow');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('S3 Snow Control with bucket and without port [108]', () {
    final resolved = resolveEndpoint(
        region: 'snow',
        bucket: 'bucketName',
        endpoint: 'https://10.0.1.12',
        useFips: false,
        useDualStack: false);
    expect(resolved.url, 'https://10.0.1.12');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'snow');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('S3 Snow Control with bucket and with DNS [109]', () {
    final resolved = resolveEndpoint(
        region: 'snow',
        bucket: 'bucketName',
        endpoint: 'http://s3snow.com',
        useFips: false,
        useDualStack: false);
    expect(resolved.url, 'http://s3snow.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3');
    expect(resolved.authSchemes[0].signingRegion, 'snow');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('S3 Snow Control with FIPS enabled [110]', () {
    expect(
      () => resolveEndpoint(
          region: 'snow',
          bucket: 'bucketName',
          endpoint: 'https://10.0.1.12:433',
          useFips: true,
          useDualStack: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'S3 Snow does not support FIPS')),
    );
  });
  test('S3 Snow Control with Dualstack enabled [111]', () {
    expect(
      () => resolveEndpoint(
          region: 'snow',
          bucket: 'bucketName',
          endpoint: 'https://10.0.1.12:433',
          useFips: false,
          useDualStack: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'S3 Snow does not support DualStack')),
    );
  });
  test('Tagging on express bucket routed to s3express-control [112]', () {
    final resolved = resolveEndpoint(
        resourceArn:
            'arn:aws:s3express:us-east-1:871317572157:bucket/crachlintest--use1-az4--x-s3',
        accountId: '871317572157',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3express-control.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Tagging on express ap routed to s3express-control [113]', () {
    final resolved = resolveEndpoint(
        resourceArn:
            'arn:aws:s3express:us-east-1:871317572157:accesspoint/crachlintest--use1-az4--xa-s3',
        accountId: '871317572157',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3express-control.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Tagging on express bucket routed to s3express-control FIPS when FIPS enabled [114]',
      () {
    final resolved = resolveEndpoint(
        resourceArn:
            'arn:aws:s3express:us-east-1:871317572157:bucket/crachlintest--use1-az4--x-s3',
        accountId: '871317572157',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(
        resolved.url, 'https://s3express-control-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Tagging on express bucket cn routed to s3express-control china endpoint [115]',
      () {
    final resolved = resolveEndpoint(
        resourceArn:
            'arn:aws-cn:s3express:cn-north-1:871317572157:bucket/crachlintest--use1-az4--x-s3',
        accountId: '871317572157',
        region: 'cn-north-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(
        resolved.url, 'https://s3express-control.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'cn-north-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Tagging on express bucket cn routed to s3express-control china endpoint with FIPS [116]',
      () {
    expect(
      () => resolveEndpoint(
          resourceArn:
              'arn:aws-cn:s3express:cn-north-1:871317572157:bucket/crachlintest--use1-az4--x-s3',
          accountId: '871317572157',
          region: 'cn-north-1',
          requiresAccountId: true,
          useDualStack: false,
          useFips: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Partition does not support FIPS')),
    );
  });
  test(
      'Tagging on express bucket with custom endpoint routed to custom endpoint [117]',
      () {
    final resolved = resolveEndpoint(
        resourceArn:
            'arn:aws:s3express:us-east-1:871317572157:bucket/crachlintest--use1-az4--x-s3',
        endpoint: 'https://my-endpoint.express-control.s3.aws.dev',
        accountId: '871317572157',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://my-endpoint.express-control.s3.aws.dev');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Tagging on express access point with custom endpoint routed to custom endpoint [118]',
      () {
    final resolved = resolveEndpoint(
        resourceArn:
            'arn:aws:s3express:us-east-1:871317572157:accesspoint/crachlintest--use1-az4--xa-s3',
        endpoint: 'https://my-endpoint.express-control.s3.aws.dev',
        accountId: '871317572157',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://my-endpoint.express-control.s3.aws.dev');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Tagging on express bucket with dualstack and custom endpoint fails [119]',
      () {
    expect(
      () => resolveEndpoint(
          resourceArn:
              'arn:aws:s3express:us-east-1:871317572157:bucket/crachlintest--use1-az4--x-s3',
          endpoint: 'https://my-endpoint.express-control.s3.aws.dev',
          accountId: '871317572157',
          region: 'us-east-1',
          requiresAccountId: true,
          useDualStack: true,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: DualStack and custom endpoint are not supported')),
    );
  });
  test('Access Point APIs on express bucket routed to s3express-control [120]',
      () {
    final resolved = resolveEndpoint(
        accountId: '871317572157',
        accessPointName: 'myaccesspoint--abcd-ab1--xa-s3',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3express-control.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Access Point APIs on express bucket routed to s3express-control for List [121]',
      () {
    final resolved = resolveEndpoint(
        accountId: '871317572157',
        region: 'us-east-1',
        useS3ExpressControlEndpoint: true,
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://s3express-control.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Access Point APIs on express bucket routed to s3express-control for FIPS [122]',
      () {
    final resolved = resolveEndpoint(
        accountId: '871317572157',
        accessPointName: 'myaccesspoint--abcd-ab1--xa-s3',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(
        resolved.url, 'https://s3express-control-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Access Point APIs on express bucket routed to s3express-control for FIPS for List [123]',
      () {
    final resolved = resolveEndpoint(
        accountId: '871317572157',
        region: 'us-east-1',
        useS3ExpressControlEndpoint: true,
        requiresAccountId: true,
        useDualStack: false,
        useFips: true);
    expect(
        resolved.url, 'https://s3express-control-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Access Point APIs on express bucket routed to s3express-control for china region [124]',
      () {
    final resolved = resolveEndpoint(
        accessPointName: 'myaccesspoint--abcd-ab1--xa-s3',
        accountId: '871317572157',
        region: 'cn-north-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(
        resolved.url, 'https://s3express-control.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'cn-north-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Access Point APIs on express bucket routed to s3express-control for china region for List [125]',
      () {
    final resolved = resolveEndpoint(
        accountId: '871317572157',
        region: 'cn-north-1',
        useS3ExpressControlEndpoint: true,
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(
        resolved.url, 'https://s3express-control.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'cn-north-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Error when Access Point APIs on express bucket routed to s3express-control for china and FIPS [126]',
      () {
    expect(
      () => resolveEndpoint(
          accountId: '871317572157',
          region: 'cn-north-1',
          requiresAccountId: true,
          useDualStack: false,
          useFips: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message, 'message', 'Partition does not support FIPS')),
    );
  });
  test(
      'Error Access Point APIs on express bucket routed to s3express-control invalid zone [127]',
      () {
    expect(
      () => resolveEndpoint(
          accessPointName: 'myaccesspoint-garbage-zone--xa-s3',
          accountId: '871317572157',
          region: 'us-east-1',
          requiresAccountId: true,
          useDualStack: false,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Unrecognized S3Express Access Point name format.')),
    );
  });
  test(
      'Access Point APIs on express bucket routed to custom endpoint if provided [128]',
      () {
    final resolved = resolveEndpoint(
        accountId: '871317572157',
        accessPointName: 'myaccesspoint--abcd-ab1--xa-s3',
        endpoint: 'https://my-endpoint.express-control.s3.aws.dev',
        region: 'us-east-1',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://my-endpoint.express-control.s3.aws.dev');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'Access Point APIs on express bucket routed to custom endpoint if provided for List [129]',
      () {
    final resolved = resolveEndpoint(
        accountId: '871317572157',
        region: 'us-east-1',
        useS3ExpressControlEndpoint: true,
        endpoint: 'https://my-endpoint.express-control.s3.aws.dev',
        requiresAccountId: true,
        useDualStack: false,
        useFips: false);
    expect(resolved.url, 'https://my-endpoint.express-control.s3.aws.dev');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, 's3express');
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Error on Access Point APIs on express bucket for dual stack [130]', () {
    expect(
      () => resolveEndpoint(
          accountId: '871317572157',
          accessPointName: 'myaccesspoint--abcd-ab1--xa-s3',
          region: 'us-east-1',
          requiresAccountId: true,
          useDualStack: true,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'S3Express does not support Dual-stack.')),
    );
  });
  test(
      'Error Access Point APIs on express bucket for dual stack for List [131]',
      () {
    expect(
      () => resolveEndpoint(
          accountId: '871317572157',
          region: 'us-east-1',
          useS3ExpressControlEndpoint: true,
          requiresAccountId: true,
          useDualStack: true,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'S3Express does not support Dual-stack.')),
    );
  });
  test(
      'Error on Access Point APIs on express bucket for custom endpoint and dual stack [132]',
      () {
    expect(
      () => resolveEndpoint(
          accountId: '871317572157',
          accessPointName: 'myaccesspoint--abcd-ab1--xa-s3',
          endpoint: 'https://my-endpoint.express-control.s3.aws.dev',
          region: 'us-east-1',
          requiresAccountId: true,
          useDualStack: true,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: DualStack and custom endpoint are not supported')),
    );
  });
  test(
      'Error Access Point APIs on express bucket for custom endpoint and dual stack for List [133]',
      () {
    expect(
      () => resolveEndpoint(
          accountId: '871317572157',
          region: 'us-east-1',
          useS3ExpressControlEndpoint: true,
          endpoint: 'https://my-endpoint.express-control.s3.aws.dev',
          requiresAccountId: true,
          useDualStack: true,
          useFips: false),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: DualStack and custom endpoint are not supported')),
    );
  });
}
