// AUTO-GENERATED: This file is generated by the `generator` package.
//
// Endpoint resolution conformance tests, derived from the service's
// `smithy.rules#endpointTests` trait.

// ignore_for_file: prefer_single_quotes, prefer_collection_literals, unnecessary_lambdas, unused_import

import 'package:aws_client/src/generated/iot_secure_tunneling/v2018_10_05.endpoints.dart';
import 'package:aws_client/src/shared/src/protocol/endpoints/endpoint_resolver.dart';
import 'package:test/test.dart';

void main() {
  test('For region ap-east-1 with FIPS disabled and DualStack disabled [0]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.ap-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ap-east-1 with FIPS disabled and DualStack enabled [1]', () {
    final resolved = resolveEndpoint(
        region: 'ap-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.ap-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-northeast-1 with FIPS disabled and DualStack disabled [2]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-northeast-1', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.ap-northeast-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ap-northeast-1 with FIPS disabled and DualStack enabled [3]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-northeast-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.ap-northeast-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-northeast-2 with FIPS disabled and DualStack disabled [4]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-northeast-2', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.ap-northeast-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ap-northeast-2 with FIPS disabled and DualStack enabled [5]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-northeast-2', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.ap-northeast-2.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ap-south-1 with FIPS disabled and DualStack disabled [6]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-south-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.ap-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ap-south-1 with FIPS disabled and DualStack enabled [7]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-south-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.ap-south-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-southeast-1 with FIPS disabled and DualStack disabled [8]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-southeast-1', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.ap-southeast-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ap-southeast-1 with FIPS disabled and DualStack enabled [9]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-southeast-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.ap-southeast-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-southeast-2 with FIPS disabled and DualStack disabled [10]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-southeast-2', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.ap-southeast-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region ap-southeast-2 with FIPS disabled and DualStack enabled [11]',
      () {
    final resolved = resolveEndpoint(
        region: 'ap-southeast-2', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.ap-southeast-2.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ca-central-1 with FIPS disabled and DualStack disabled [12]',
      () {
    final resolved = resolveEndpoint(
        region: 'ca-central-1', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.ca-central-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ca-central-1 with FIPS enabled and DualStack disabled [13]',
      () {
    final resolved = resolveEndpoint(
        region: 'ca-central-1', useFips: true, useDualStack: false);
    expect(resolved.url,
        'https://api.tunneling.iot-fips.ca-central-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ca-central-1 with FIPS disabled and DualStack enabled [14]',
      () {
    final resolved = resolveEndpoint(
        region: 'ca-central-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.ca-central-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region ca-central-1 with FIPS enabled and DualStack enabled [15]',
      () {
    final resolved = resolveEndpoint(
        region: 'ca-central-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling-fips.ca-central-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-central-1 with FIPS disabled and DualStack disabled [16]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-central-1', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.eu-central-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-central-1 with FIPS disabled and DualStack enabled [17]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-central-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.eu-central-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-north-1 with FIPS disabled and DualStack disabled [18]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-north-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.eu-north-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-north-1 with FIPS disabled and DualStack enabled [19]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-north-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.eu-north-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-1 with FIPS disabled and DualStack disabled [20]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.eu-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-1 with FIPS disabled and DualStack enabled [21]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.eu-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-2 with FIPS disabled and DualStack disabled [22]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.eu-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-2 with FIPS disabled and DualStack enabled [23]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-2', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.eu-west-2.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-3 with FIPS disabled and DualStack disabled [24]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-3', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.eu-west-3.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region eu-west-3 with FIPS disabled and DualStack enabled [25]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-west-3', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.eu-west-3.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region me-central-1 with FIPS disabled and DualStack disabled [26]',
      () {
    final resolved = resolveEndpoint(
        region: 'me-central-1', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.me-central-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region me-central-1 with FIPS disabled and DualStack enabled [27]',
      () {
    final resolved = resolveEndpoint(
        region: 'me-central-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.me-central-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region me-south-1 with FIPS disabled and DualStack disabled [28]',
      () {
    final resolved = resolveEndpoint(
        region: 'me-south-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.me-south-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region me-south-1 with FIPS disabled and DualStack enabled [29]',
      () {
    final resolved = resolveEndpoint(
        region: 'me-south-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.me-south-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region sa-east-1 with FIPS disabled and DualStack disabled [30]',
      () {
    final resolved = resolveEndpoint(
        region: 'sa-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.sa-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region sa-east-1 with FIPS disabled and DualStack enabled [31]',
      () {
    final resolved = resolveEndpoint(
        region: 'sa-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.sa-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack disabled [32]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS enabled and DualStack disabled [33]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: true, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack enabled [34]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS enabled and DualStack enabled [35]', () {
    final resolved =
        resolveEndpoint(region: 'us-east-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-2 with FIPS disabled and DualStack disabled [36]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-2 with FIPS enabled and DualStack disabled [37]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-2', useFips: true, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot-fips.us-east-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-2 with FIPS disabled and DualStack enabled [38]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-2', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.us-east-2.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-2 with FIPS enabled and DualStack enabled [39]', () {
    final resolved =
        resolveEndpoint(region: 'us-east-2', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling-fips.us-east-2.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-1 with FIPS disabled and DualStack disabled [40]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.us-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-1 with FIPS enabled and DualStack disabled [41]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1', useFips: true, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot-fips.us-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-1 with FIPS disabled and DualStack enabled [42]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.us-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-1 with FIPS enabled and DualStack enabled [43]', () {
    final resolved =
        resolveEndpoint(region: 'us-west-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling-fips.us-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-2 with FIPS disabled and DualStack disabled [44]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-2', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-2 with FIPS enabled and DualStack disabled [45]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-2', useFips: true, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot-fips.us-west-2.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-2 with FIPS disabled and DualStack enabled [46]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-west-2', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.us-west-2.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-west-2 with FIPS enabled and DualStack enabled [47]', () {
    final resolved =
        resolveEndpoint(region: 'us-west-2', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling-fips.us-west-2.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS disabled and DualStack disabled [48]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS disabled and DualStack enabled [49]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: false, useDualStack: true);
    expect(resolved.url,
        'https://api.iot-tunneling.cn-north-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region cn-northwest-1 with FIPS disabled and DualStack disabled [50]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1', useFips: false, useDualStack: false);
    expect(resolved.url,
        'https://api.tunneling.iot.cn-northwest-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region cn-northwest-1 with FIPS disabled and DualStack enabled [51]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1', useFips: false, useDualStack: true);
    expect(resolved.url,
        'https://api.iot-tunneling.cn-northwest-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS enabled and DualStack enabled [52]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: true, useDualStack: true);
    expect(resolved.url,
        'https://api.iot-tunneling-fips.cn-north-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-north-1 with FIPS enabled and DualStack disabled [53]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-north-1', useFips: true, useDualStack: false);
    expect(resolved.url,
        'https://api.tunneling.iot-fips.cn-north-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-gov-east-1 with FIPS disabled and DualStack disabled [54]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS enabled and DualStack disabled [55]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: true, useDualStack: false);
    expect(resolved.url,
        'https://api.tunneling.iot-fips.us-gov-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS disabled and DualStack enabled [56]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.us-gov-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-east-1 with FIPS enabled and DualStack enabled [57]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-east-1', useFips: true, useDualStack: true);
    expect(
        resolved.url, 'https://api.iot-tunneling-fips.us-gov-east-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-gov-west-1 with FIPS disabled and DualStack disabled [58]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.us-gov-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-west-1 with FIPS enabled and DualStack disabled [59]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: true, useDualStack: false);
    expect(resolved.url,
        'https://api.tunneling.iot-fips.us-gov-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-west-1 with FIPS disabled and DualStack enabled [60]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://api.iot-tunneling.us-gov-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-west-1 with FIPS enabled and DualStack enabled [61]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: true, useDualStack: true);
    expect(
        resolved.url, 'https://api.iot-tunneling-fips.us-gov-west-1.api.aws');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-iso-east-1 with FIPS disabled and DualStack disabled [62]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://api.tunneling.iot.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-iso-east-1 with FIPS enabled and DualStack disabled [63]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1', useFips: true, useDualStack: false);
    expect(resolved.url,
        'https://api.tunneling.iot-fips.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isob-east-1 with FIPS disabled and DualStack disabled [64]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1', useFips: false, useDualStack: false);
    expect(
        resolved.url, 'https://api.tunneling.iot.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isob-east-1 with FIPS enabled and DualStack disabled [65]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1', useFips: true, useDualStack: false);
    expect(resolved.url,
        'https://api.tunneling.iot-fips.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For custom endpoint with region set and fips disabled and dualstack disabled [66]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1',
        useFips: false,
        useDualStack: false,
        endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For custom endpoint with region not set and fips disabled and dualstack disabled [67]',
      () {
    final resolved = resolveEndpoint(
        useFips: false, useDualStack: false, endpoint: 'https://example.com');
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For custom endpoint with fips enabled and dualstack disabled [68]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: true,
          useDualStack: false,
          endpoint: 'https://example.com'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: FIPS and custom endpoint are not supported')),
    );
  });
  test('For custom endpoint with fips disabled and dualstack enabled [69]', () {
    expect(
      () => resolveEndpoint(
          region: 'us-east-1',
          useFips: false,
          useDualStack: true,
          endpoint: 'https://example.com'),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: Dualstack and custom endpoint are not supported')),
    );
  });
  test('Missing region [70]', () {
    expect(
      () => resolveEndpoint(),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid Configuration: Missing Region')),
    );
  });
}
