// AUTO-GENERATED: This file is generated by the `generator` package.
//
// Endpoint resolution conformance tests, derived from the service's
// `smithy.rules#endpointTests` trait.

// ignore_for_file: prefer_single_quotes, prefer_collection_literals, unnecessary_lambdas, unused_import

import 'package:aws_client/src/generated/account/v2021_02_01.endpoints.dart';
import 'package:aws_client/src/shared/src/protocol/endpoints/endpoint_resolver.dart';
import 'package:test/test.dart';

void main() {
  test('For custom endpoint with region not set and fips disabled [0]', () {
    final resolved =
        resolveEndpoint(endpoint: 'https://example.com', useFips: false);
    expect(resolved.url, 'https://example.com');
    expect(resolved.authSchemes.length, 0);
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For custom endpoint with fips enabled [1]', () {
    expect(
      () => resolveEndpoint(endpoint: 'https://example.com', useFips: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: FIPS and custom endpoint are not supported')),
    );
  });
  test('For custom endpoint with fips disabled and dualstack enabled [2]', () {
    expect(
      () => resolveEndpoint(
          endpoint: 'https://example.com', useFips: false, useDualStack: true),
      throwsA(isA<EndpointResolutionException>().having(
          (e) => e.message,
          'message',
          'Invalid Configuration: Dualstack and custom endpoint are not supported')),
    );
  });
  test('For region us-east-1 with FIPS enabled and DualStack enabled [3]', () {
    final resolved =
        resolveEndpoint(region: 'us-east-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://account-fips.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS enabled and DualStack disabled [4]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://account-fips.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack enabled [5]', () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://account.us-east-1.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-east-1 with FIPS disabled and DualStack disabled [6]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://account.us-east-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-northwest-1 with FIPS enabled and DualStack enabled [7]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1', useFips: true, useDualStack: true);
    expect(resolved.url,
        'https://account-fips.cn-northwest-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'cn-northwest-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-northwest-1 with FIPS enabled and DualStack disabled [8]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1', useFips: true, useDualStack: false);
    expect(
        resolved.url, 'https://account-fips.cn-northwest-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'cn-northwest-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region cn-northwest-1 with FIPS disabled and DualStack enabled [9]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1', useFips: false, useDualStack: true);
    expect(resolved.url,
        'https://account.cn-northwest-1.api.amazonwebservices.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'cn-northwest-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region cn-northwest-1 with FIPS disabled and DualStack disabled [10]',
      () {
    final resolved = resolveEndpoint(
        region: 'cn-northwest-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://account.cn-northwest-1.amazonaws.com.cn');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'cn-northwest-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region eusc-de-east-1 with FIPS enabled and DualStack disabled [11]',
      () {
    final resolved = resolveEndpoint(
        region: 'eusc-de-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://account-fips.eusc-de-east-1.amazonaws.eu');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'eusc-de-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region eusc-de-east-1 with FIPS disabled and DualStack disabled [12]',
      () {
    final resolved = resolveEndpoint(
        region: 'eusc-de-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://account.eusc-de-east-1.amazonaws.eu');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'eusc-de-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-iso-east-1 with FIPS enabled and DualStack disabled [13]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://account-fips.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-iso-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-iso-east-1 with FIPS disabled and DualStack disabled [14]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-iso-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://account.us-iso-east-1.c2s.ic.gov');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-iso-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isob-east-1 with FIPS enabled and DualStack disabled [15]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://account-fips.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-isob-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isob-east-1 with FIPS disabled and DualStack disabled [16]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isob-east-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://account.us-isob-east-1.sc2s.sgov.gov');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-isob-east-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region eu-isoe-west-1 with FIPS enabled and DualStack disabled [17]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-isoe-west-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://account-fips.eu-isoe-west-1.cloud.adc-e.uk');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'eu-isoe-west-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region eu-isoe-west-1 with FIPS disabled and DualStack disabled [18]',
      () {
    final resolved = resolveEndpoint(
        region: 'eu-isoe-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://account.eu-isoe-west-1.cloud.adc-e.uk');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'eu-isoe-west-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isof-south-1 with FIPS enabled and DualStack disabled [19]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isof-south-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://account-fips.us-isof-south-1.csp.hci.ic.gov');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-isof-south-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-isof-south-1 with FIPS disabled and DualStack disabled [20]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-isof-south-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://account.us-isof-south-1.csp.hci.ic.gov');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-isof-south-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-west-1 with FIPS enabled and DualStack enabled [21]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: true, useDualStack: true);
    expect(resolved.url, 'https://account-fips.us-gov-west-1.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-west-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-west-1 with FIPS enabled and DualStack disabled [22]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: true, useDualStack: false);
    expect(resolved.url, 'https://account-fips.us-gov-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-west-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('For region us-gov-west-1 with FIPS disabled and DualStack enabled [23]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: false, useDualStack: true);
    expect(resolved.url, 'https://account.us-gov-west-1.api.aws');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-west-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test(
      'For region us-gov-west-1 with FIPS disabled and DualStack disabled [24]',
      () {
    final resolved = resolveEndpoint(
        region: 'us-gov-west-1', useFips: false, useDualStack: false);
    expect(resolved.url, 'https://account.us-gov-west-1.amazonaws.com');
    expect(resolved.authSchemes.length, 1);
    expect(resolved.authSchemes[0].name, 'sigv4');
    expect(resolved.authSchemes[0].signingName, isNull);
    expect(resolved.authSchemes[0].signingRegion, 'us-gov-west-1');
    expect(resolved.headers.keys.toSet(), [].toSet());
  });
  test('Missing region [25]', () {
    expect(
      () => resolveEndpoint(),
      throwsA(isA<EndpointResolutionException>().having((e) => e.message,
          'message', 'Invalid Configuration: Missing Region')),
    );
  });
}
