# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - smoke_test:
    - group:
        - dartfmt
        - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - test: -j 1 --run-skipped
