name: Analyze all apis
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    name: Analyze all apis
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v2

      - name: Print Dart SDK version
        run: dart --version

      - name: Generate all apis
        run: dart pub get && dart bin/generate.dart generate --no-pub
        working-directory: generator

      - name: Analyze all_apis package
        run: dart pub get && dart analyze --fatal-warnings --fatal-infos
        working-directory: all_apis

      - name: "check for uncommitted changes"
        run: git diff --exit-code --stat -- .
